### ISSUE TITLE
Local HTML bug

### ISSUE THREAD

**Issue by HaijunWei** [fluttercommunity/flutter_webview_plugin#114]
I loaded an HTML from the sandbox and found that the css file was not loaded. I found a problem after reading the source code. In `FlutterWebviewPlugin.m` line 109
```
[self.webview loadFileURL:htmlUrl allowingReadAccessToURL:htmlUrl];
```
If allowingReadAccessToURL is a directory, the css file can be loaded.
Is it possible to add a directory parameter to allowingReadAccessToURL？

Reference:
https://www.jianshu.com/p/663c63db9b0f

**Comment by captainjapeng** [comment]
I'm also having this issue, assets won't load from the cache directory. Is there a way to pass the value to the allowingReadAccessToURL parameter of WKWebView?

**Comment by charafau** [comment]
There's not but I'm happy to add parameters if someone will tell me what and how to add it (also, PRs are more than welcomed)

**Comment by HaijunWei** [comment]
You can add a parameter for `launch` and `reloadUrl`.
eg:
```
flutterWebViewPlugin.launch(htmlURL, readAccessToURL: xxxx)
flutterWebViewPlugin.reloadUrl(htmlURL, readAccessToURL: xxxx)
```
in In FlutterWebviewPlugin.m line 143 or line 193...199
```
NSURL *readAccessToURL = [NSURL fileURLWithPath:call.arguments[@"readAccessToURL"]];
[self.webview loadFileURL:htmlUrl allowingReadAccessToURL:readAccessToURL];
```
