### ISSUE TITLE
Does not scroll when keyboard is appeared on focus of text field

### ISSUE THREAD

**Issue by marica27** [fluttercommunity/flutter_webview_plugin#128]
I do Instagram implicit authentification and show login page in webview_plagin using WebViewScaffold. Page is short, so no scroll. When focus on any text field (username and password) keyboard are appeared and I can not see input field anymore.

Is there a way to add a scrolling?

**Comment by julindra** [comment]
I have the same issue with version 0.2.0, have you fixed it?

**Comment by lejard-h** [comment]
Hey, do you have the issue on Android or iOS or both ?

**Comment by julindra** [comment]
I have try on both Android and iOS, and the issue only appears on Android

**Comment by julindra** [comment]
any progress or info for this issue?

**Comment by marica27** [comment]
@lejard-h is there estimation when this bug will be fixed?

**Comment by m-dimov** [comment]
I also have the same issue on Android (it works fine on iOS).
When the keyboard appears, the viewable height is not refreshed for scrolling. So depending on how much (or at all) you can scroll initially, the keyboard will cover some of the content and you wont be able to scroll down to view the lower part of the website. Even the text input box you clicked might be covered by the keyboard, so you can't even see what you are typing.

**Comment by Ahmzyjazzy** [comment]
I still have this same issue on Android. Keyboard covers part of my page when i focus on any input and it doesn't scroll

**Comment by npm-ued** [comment]
I still have this same issue on Android. Keyboard covers part of my page when i focus on any input and it doesn't scroll ，the Version is flutter_webview_plugin: 0.3.10+1 @slightfoot

**Comment by OzzyOzmen** [comment]
u should use SingleChildScrollView

**Comment by npm-ued** [comment]
> u should use SingleChildScrollView

the webview input not work

**Comment by npm-ued** [comment]
@OzzyOzmen

**Comment by npm-ued** [comment]
you  can use from https://github.com/npm-ued/flutter_webview_plugin with pubspec.yaml

**Comment by npm-ued** [comment]
@Ahmzyjazzy
