### ISSUE TITLE
webview giving error on android

### ISSUE THREAD

**Issue by manujbahl** [fluttercommunity/flutter_webview_plugin#158]
Any ideas on this compile error?

/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java:100: error: cannot find symbol
        observableWebView = (ObservableWebView) webView;
        ^
  symbol:   variable observableWebView
  location: class WebviewManager

pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java:103: error: cannot find symbol
                Map<String, Object> yDirection = new HashMap<>();
                                                     ^
  symbol: class HashMap

pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java:106: error: cannot find symbol
                Map<String, Object> xDirection = new HashMap<>();
                                                     ^
  symbol: class HashMap

pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java:101: error: cannot find symbol
        observableWebView.setOnScrollChangedCallback(new ObservableWebView.OnScrollChangedCallback(){
        ^
  symbol:   variable observableWebView
  location: class WebviewManager
Note: 
pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

**Comment by MallorcaSoftware** [comment]
Updating flutter_webview_plugin to ^0.3.3 should fix the problem.
