### ISSUE TITLE
Lots of bugs on IOS use case

### ISSUE THREAD

**Issue by AskYous** [fluttercommunity/flutter_webview_plugin#171]
I don't know how to explain this but I uploaded a video here:
https://gfycat.com/RealisticRaggedHuman

I get two errors. One is really long and I don't know how to explain it. The other is due to a weird symbol. I don't have abnormal characters in my code or strings.

If needed, I can share some more information about my code.

**Comment by slightfoot** [comment]
Crash #77 resolved in latest build. `v0.3.0+2`
