### ISSUE TITLE
Expose webview estimated loading progress value in Flutter

### ISSUE THREAD

**Issue by florisvdg** [fluttercommunity/flutter_webview_plugin#177]
It would be great to be able to subscribe to the webview's estimated progress value in Flutter, backed by the `estimatedProgress` value in iOS and the `onProgressChanged` callback on Android. With that in data available we can show a sliding progress bar as a widget in Flutter.

On iOS that would be:
```
webView.addObserver(self, forKeyPath: #keyPath(WKWebView.estimatedProgress), options: .new, context: nil)
```

On Android:
```
webView.setWebChromeClient(new WebChromeClient() {
   public void onProgressChanged(WebView view, int progress) {

   }
}
```

**Comment by slightfoot** [comment]
relates to #232

**Comment by florisvdg** [comment]
Fixed in https://github.com/fluttercommunity/flutter_webview_plugin/pull/255.
