### ISSUE TITLE
Doesn't run on IOS at all. Works on Android.

### ISSUE THREAD

**Issue by willvlad** [fluttercommunity/flutter_webview_plugin#180]
Doesn't load any web pages. The scaffold loads fine, but the body doesn't load regardless of the site.

`flutter: WebViewState.shouldStart`
`flutter: WebViewState.startLoad`

Never gets to finishLoad unfortunately.

Has anyone managed to run it on IOS simulator? Some sample code would be most appreciated as the example in the docs doesn't work.

**Comment by willvlad** [comment]
Urls tested are all https of course.

**Comment by bertbeck** [comment]
I've gotten it to work on the IOS simulator - iPhone 6 Plus 11.2.
However - when I run on my iPhone 6 Plus 10.3, the webview never works.
Has anyone gotten this to work on an iPhone 6 Plus? Maybe there is an IOS version dependency
<img width="376" alt="screen shot 2018-09-12 at 1 44 28 pm" src="https://user-images.githubusercontent.com/6159170/45446259-09299280-b692-11e8-8c21-f39a9baa2862.png">. I used the sample code.

**Comment by armenarmen** [comment]
@bertbeck n00b question, where do I find the plist when I'm working with flutter? 

It's been years since I've done any mobile development and it's showing...

**Comment by SebastianEngel** [comment]
Thanks @bertbeck 👍 

@armenarmen You need to edit "ios/Runner/Info.plist".

**Comment by SebastianEngel** [comment]
> App Transport Security (ATS) is enabled by default for apps linked against the iOS 9.0 or macOS 10.11 SDKs or later. … With ATS enabled, HTTP connections must use HTTPS (RFC 2818). Attempts to connect using insecure HTTP fail. 


Source: [NSAppTransportSecurity](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity)

Same for Android:

> Starting with Android 9 (API level 28), cleartext support is disabled by default.

Source: [CleartextTrafficPermitted](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted)

So in order to use HTTP traffic you need to explicitly allow it.

**Comment by SebastianEngel** [comment]
I think this issue can be closed then.

**Comment by slightfoot** [comment]
Closing.
