### ISSUE TITLE
Screenshot of current webview

### ISSUE THREAD

**Issue by marianoarga** [fluttercommunity/flutter_webview_plugin#181]
Using RenderRepaintBoundary tecnique to take a screenshot of the webview returns an image with the CircularProgressIndicator widget instead of the already loaded URL, do you have an alternative for this? maybe RenderRepaintBoundary is relading the widget before taking the actual "canvas" image?

> takescrshot() async {
>   RenderRepaintBoundary boundary = scr.currentContext.findRenderObject();
>   var image = await boundary.toImage();
>   var byteData = await image.toByteData(format: ImageByteFormat.png);
>   var pngBytes = byteData.buffer.asUint8List();
>   print(pngBytes);
> }

**Comment by erdemyerebasmaz** [comment]
@marianoarga Have you found a solution to this problem?

**Comment by marianoarga** [comment]
@erdemyerebasmaz No, I continue without screenshot feature.

**Comment by charafau** [comment]
it's not posible to take a screenshot of webview, because of the way plugin works - it's native android activity with flutter view on top. 

I dont know what your use case is, but you need to fallback to native code of given platform to take screenshot. 

Therefore, it's not possible with plugin now, closing.

**Comment by erdemyerebasmaz** [comment]
@charafau I'd like to show a dialog with webview visible on background, afaik this is not possible at the moment. That's why I wanted to show webview's screenshot as a widget and hide the webview till the action from dialog is complete.
I will inject an external library to capture screenshot, convert the image back to raw data and probably send it via a post message back to flutter app.

**Comment by charafau** [comment]
@erdemyerebasmaz  I don't know your use-case but I think it's out of scope from this project. I think I should add it in readme, this webview was created to have something to authenticate with oauth2, display simple webpages, until Google will make their own main webview.

**Comment by erdemyerebasmaz** [comment]
For those who still want to take screenshot of the visible webview and pass it back to Flutter:

I solved this issue in this [PR](https://github.com/breez/flutter_webview_plugin/pull/2/files) of a forked repository.

! Please note that you need to fork the plugin and add these changes, this is not supported by the official plugin as it is out of it's scope !

Just a small and incomplete example to use it on your Flutter app, 
**Pseudocode:**
```
final _webview = new FlutterWebviewPlugin();
Uint8List  _screenshotData;

//Call this where you need the screenshot:
_getScreenshot().whenComplete(() {
    // Wait for memory image to load
     Timer(Duration(milliseconds: 100), () {
    // For our use case, we needed to hide Webview to interact with an AlertDialog
        _webview.hide();
    });
});
//_getScreenshot is just a local function on our Flutter app, don't confuse it with plugins takeScreenshot()
Future _getScreenshot() async {
   // This is where we take the screenshot with plugin, 
    Uint8List _imageData = await _webview.takeScreenshot(); 
    setState(() {
      _screenshotData = _imageData;
    });
  }

WebviewScaffold(
...
    initialChild: _screenshotData != null ? Image.memory(_screenshotData) : (Your Placeholder Widget),
...
);

```

**Comment by marianoarga** [comment]
@erdemyerebasmaz Thanks for your effort <3, unfortunately I'm kinda out of this app by the moment, but I'm sure this will help many developers using webviews.
