### ISSUE TITLE
WebView not loading Mixed Content

### ISSUE THREAD

**Issue by YueYongDev** [fluttercommunity/flutter_webview_plugin#191]
I'm trying to make a app with WebView,  the website is using https, but the content (ex. mp3 file) uses http, how can i fix the "Mixed Content" problem in flutter?

**Comment by slightfoot** [comment]
Should be fixed as of `v0.3.0+2`. Please retest.

**Comment by mineralres** [comment]
webview_flutter: ^0.3.10+4  still has the problem

**Comment by ljx0517** [comment]
18 Nov 2019 still has the problem
