### ISSUE TITLE
How to get loaded web page title?

### ISSUE THREAD

**Issue by yeahia2508** [fluttercommunity/flutter_webview_plugin#192]
I have a requirement to change the app title based on the page user currently loaded. is there any way to get page title?

**Comment by jonnytest1** [comment]
did u try evaluate javascript with document.title ?

**Comment by fccoelho** [comment]
> did u try evaluate javascript with document.title ?

Sure, but how to get a reference to the Document?

**Comment by baoxiehao** [comment]
> > did u try evaluate javascript with document.title ?
> 
> Sure, but how to get a reference to the Document?

You can refer to my code snippet, it works for me:

`class WebViewPage extends StatefulWidget {
  final String title;
  final String url;

  const WebViewPage({
    Key key,
    @required this.title,
    @required this.url,
  }) : super(key: key);

  @override
  _WebViewPageState createState() => new _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  String title;
  final flutterWebViewPlugin = FlutterWebviewPlugin();

  @override
  void initState() {
    super.initState();
    title = widget.title;
    flutterWebViewPlugin.onStateChanged.listen((state) async {
      if (state.type == WebViewState.finishLoad) {
        String script = 'window.document.title';
        var title = await flutterWebViewPlugin.evalJavascript(script);
        setState(() {
          this.title = title;
          print('loaded TITLE: $title');
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: CustomTheme.buildTheme(),
      home: WebviewScaffold(
        appBar: AppBar(
          title: Text(title),
          leading: IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () => Router.pageBack(context),
          ),
        ),
        url: widget.url,
        hidden: true,
        withJavascript: true,
      ),
    );
  }
}`

**Comment by AlexVincent525** [comment]
@baoxiehao Hi friend, this works on android, but is this working on iOS? I haven't test yet, but I saw many issues with no javascript in iOS.

**Comment by chenxianqi** [comment]
That's how I handled it.

```
  // get website title
  Future<String> getWebTitle({String url}) async{
    final res = await http.get(url);
    String title = RegExp(r"<[t|T]{1}[i|I]{1}[t|T]{1}[l|L]{1}[e|E]{1}(\s.*)?>([^<]*)</[t|T]{1}[i|I]{1}[t|T]{1}[l|L]{1}[e|E]{1}>").stringMatch(res.data);
    if(title!=null){
      return title.substring(title.indexOf('>')+1, title.lastIndexOf("<"));
    }else{
      return "";
    }
  }


@override
  void initState() {
    super.initState();
    getWebTitle(url: widget.url);
    flutterWebviewPlugin.onUrlChanged.listen((String url) {
      getWebTitle(url: url);
    });
  }

  // use get title
  Future<void> getWebTitle({String url}) async{
    String title = await PublicService().getWebTitle(url: url);
    setState(() {
      this.title = title;
    });
  }
```

**Comment by charafau** [comment]
Seems like it's resolved ?

**Comment by fccoelho** [comment]
Haven't tested. But I think it's ok to close  this issue.

**Comment by charafau** [comment]
Closing..
