### ISSUE TITLE
Config project error in Android Studio 3.2

### ISSUE THREAD

**Issue by wanyt** [fluttercommunity/flutter_webview_plugin#205]
There is a compile error when I import the lib and run the project. This is the issue:

> Configure project :flutter_webview_plugin
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.2) for Android Gradle Plugin 3.2.0.
Android SDK Build Tools 28.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

I think you can update "buildToolVersion" to solve the problem, and release a new version.

**Comment by jordansilva** [comment]
Hi @lejard-h,
I did a small pull request updating the Android SDK Build Tools version and Gradle Plugin. 
Could you check?
