### ISSUE TITLE
Only Secure links load into WebView

### ISSUE THREAD

**Issue by jrmarkham** [fluttercommunity/flutter_webview_plugin#214]
It seems that only secure urls will load. The good news is that just adding an "s" to http does the trick.

I tested this  on scaffold and launch 

ie: 
http://mega.markhamenterprises.com (won't load)
https://mega.markhamenterprises.com (will load)

**Comment by vanelizarov** [comment]
Try setting up `NSAppTransportSecurity` like below in iOS' `Info.plist`
 
```
<dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      <key>NSExceptionDomains</key>
      <dict>
          <key>mydomain.ru</key>
          <dict>
              <key>NSExceptionAllowsInsecureHTTPLoads</key>
              <true/>
              <key>NSIncludesSubdomains</key>
              <true/>
          </dict>
      </dict>
  </dict>
```

**Comment by jrmarkham** [comment]
That did it-- thanks.

**Comment by jjjachyty** [comment]
if android how to do

**Comment by charafau** [comment]
it shouldn't be an issue on Android
