### ISSUE TITLE
check loading completed

### ISSUE THREAD

**Issue by Gyorgio88** [fluttercommunity/flutter_webview_plugin#219]
Hi guys,
first question:
How can I check the loading completed?
second question:
the return widget
new Scaffold( appBar: widget.appBar, persistentFooterButtons: widget.persistentFooterButtons, bottomNavigationBar: widget.bottomNavigationBar, body: const Center(child: const CircularProgressIndicator()));
it is not shown on loading
thanks

**Comment by jordansilva** [comment]
**First question answer:**
Did onStateChanged not work for you?
```
FlutterWebviewPlugin().onStateChanged.listen((WebViewStateChanged onData) {
      if (onData.type == WebViewState.finishLoad) {
        
      }
   });
```

**Comment by Gyorgio88** [comment]
I didn't tried, i'll keep you posted

**Comment by Gyorgio88** [comment]
it works, thanks

**Comment by charafau** [comment]
Seems like issue got resolved, closing
