### ISSUE TITLE
Can not open url in iOS

### ISSUE THREAD

**Issue by gunadharma** [fluttercommunity/flutter_webview_plugin#229]
I try to open url in Android using Flutter Webview Plugin and it works, but in iOS simulator it doesn't work. For example: I open google.com and then I search a website, I can not open the site by clicking it in google search list. Please help to resolve this..

**Comment by jordansilva** [comment]
@gunadharma It's working here. Can you describe more how you implemented the Webview Plugin or more info about your problem?
I just added a WebviewScaffold using google url, searched for "Flutter News" and clicked on the first link (which is flutterio twitter) and it worked.

**Comment by gunadharma** [comment]
Hi @jordansilva thanks for your comment, here is how i implement the plugin:
`routes: {
        "/": (_) => new MyHomePage(title:''),
        "/webview": (_) => new WebviewScaffold(
              url: url,
              appBar: AppBar(),
              withJavascript: true,
              withLocalStorage: true,
              withZoom: true,
            )
      },`

![image](https://user-images.githubusercontent.com/13472045/48066705-e7b3d580-e200-11e8-94aa-21771485f067.png)
For example: I open google then I search something. I can not open any links from the search result.

Is there any settings or code that I missed? Please help..

**Comment by gunadharma** [comment]
Oh I see. I will try to follow your way. Thank you very much @jordansilva

**Comment by gunadharma** [comment]
@jordansilva  Still can not open. I guess it is because the link is open new window/tab. not in the same window. how can we solve this?

**Comment by jordansilva** [comment]
@gunadharma 
I really don't know what are you doing... 
Check the code that I've shared:
https://gist.github.com/jordansilva/42a4dd26474418fb223bbdaec5459a8b

**Comment by gunadharma** [comment]
@jordansilva I am trying to click button which open url in the new window/tab but it won't open.

**Comment by jordansilva** [comment]
@gunadharma Check this code that I shared. I guess is the same thing that you're trying.
The first screen just has a button and when you click in this button, opens the WebView, and if you can navigate in this webview.

**Comment by gunadharma** [comment]
@jordansilva  Okay I will check the code that you shared. Thank you very much :)

**Comment by l1Dan** [comment]
Can not open url in iOS! @jordansilva
Flutter version: 0.10.3-pre.142

Widget build(BuildContext context) {
    return WebviewScaffold(
      url: 'https://www.google.com',
      appBar: AppBar(
        title: Text('Webview'),
      ),
    );
  }

Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)

**Comment by jordansilva** [comment]
@l1Dan Can you check which ```flutter channel``` are you using? I had a problem using master, so I changed to beta channel and it worked.

**Comment by l1Dan** [comment]
@jordansilva  It is working, bug hava a trouble.

**Comment by l1Dan** [comment]
@jordansilva OK!  May be the same problem. Think you so much!  
[https://github.com/flutter/flutter/issues/23962](url)

**Comment by slightfoot** [comment]
Fixed as of `v0.3.0+2`. Closing.

**Comment by deligence** [comment]
We are facing the same issue. The site with https are getting opened in Android as well as in iPhone. However sites with http are not getting loaded in iPhone.

**Comment by AstroDule** [comment]
@deligence Here is the solution: https://github.com/fluttercommunity/flutter_webview_plugin/issues/94#issuecomment-395190735

**Comment by folivi** [comment]
Same here. The webiste is being loaded on Android but I get a blank white screen on ios

**Comment by charafau** [comment]
@folivi  it should work, but you need to add keys to ios https://github.com/fluttercommunity/flutter_webview_plugin/issues/94#issuecomment-395190735

I also added this to main README
