### ISSUE TITLE
please update flutter newest version 0.11.3

### ISSUE THREAD

**Issue by NewITCorp** [fluttercommunity/flutter_webview_plugin#235]
I got an error after flutter upgrade to 0.11.3

`*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f79e1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ed3c735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f7bcf44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010f7a2ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010f7a4da8 _CF_forwarding_prep_0 + 120
	5   Runner                              0x000000010ce988d0 -[FlutterWebviewPlugin initWebview:] + 2832
	6   Runner                              0x000000010ce9779e -[FlutterWebviewPlugin handleMethodCall:result:] + 254
Lost connection to device.
	7   Flutter                             0x000000010cf4a0fb __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	8   Flutter  <…>`

so i am unable to use it now...
thank you for a great library.

**Comment by dinhha** [comment]
I fixed the issue on my fork
https://github.com/dinhha/flutter_webview_plugin/commit/aca88cb779d3f06988dcd4f8da7e6bc12456d17b

**Comment by slightfoot** [comment]
@NewITCorp @dinhha please retest with `v0.3.0+2` that has just been released, this issue should now be resolved.

**Comment by NewITCorp** [comment]
it is ok by now.
thanks for a nice library!

**Comment by dinhha** [comment]
> @NewITCorp @dinhha please retest with `v0.3.0+2` that has just been released, this issue should now be resolved.

I tested. It works well

**Comment by slightfoot** [comment]
Excellent. Thanks. Closing.
