### ISSUE TITLE
Problems using webview_plugin

### ISSUE THREAD

**Issue by xinnai** [fluttercommunity/flutter_webview_plugin#240]
1.I use bottomNavigationBar in my code,  but when I open flutter_webview_plugin and call flutterWebviewPlugin.launch the webview totally above my tabbar instead of inside one of my tab. I know I can defind the rect size but I want this webpage auto resize in my tab. And when I select another tab, it can disappear on the screen.
2. I got a link:https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html which include AR examples. This link can work well on my android with Chrome. But when I use flutter_webview_plugin.launch this url, it cann't work. Is that mean this plugin doesn't support AR or Threejs?
3. I cann't open localhost websites.

**Comment by lmcdo** [comment]
Hi, did you find a resolution for this?

**Comment by charafau** [comment]
1. This view is not in widget tree, so it won't automatically disappear, you need to close it yourself.

2. You probably need camera permissions

3. There is an issue how to do that.
