### ISSUE TITLE
WebviewScaffold fails to honor AppBar elevation

### ISSUE THREAD

**Issue by jeffmikels** [fluttercommunity/flutter_webview_plugin#242]
The WebviewScaffold fails to display the "elevation" shadow under the AppBar.

**Comment by slightfoot** [comment]
It cant. The webview is actually sitting on top of the flutter content in the Z axis. So the shadow of the app bar cannot be "over" the webview. However there other directions we'll be looking into in the future to resolve this type of issue and others.
