### ISSUE TITLE
Problems open camera 

### ISSUE THREAD

**Issue by xinnai** [fluttercommunity/flutter_webview_plugin#247]
When I use this plugin to open a url , which invocate camera and webxr, I got these errors:

I/WebViewFactory(25360): Loading com.google.android.webview version 62.0.3202.84 (code 320208450)
I/cr_LibraryLoader(25360): Time to load native libraries: 3 ms (timestamps 8071-8074)
I/chromium(25360): [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(25360): Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"
W/cr_ChildProcLH(25360): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
I/cr_BrowserStartup(25360): Initializing chromium process, singleProcess=false
W/esat.flutterapp(25360): type=1400 audit(0.0:45259): avc: denied { read } for name="vmstat" dev="proc" ino=4026532141
scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
W/cr_CrashFileManager(25360): /data/user/0/com.piesat.flutterapp/cache/WebView/Crash Reports does not exist or is not a directory
W/cr_media(25360): Requires BLUETOOTH permission
I/cr_LibraryLoader(25360): Using linker: org.chromium.base.library_loader.ModernLinker
W/AudioCapabilities(25360): Unsupported mime audio/adpcm
W/AudioCapabilities(25360): Unsupported mime audio/x-ms-adpcm
W/AudioCapabilities(25360): Unsupported mime audio/alac
W/AudioCapabilities(25360): Unsupported mime audio/ape
W/AudioCapabilities(25360): Unsupported mime audio/dsd
W/AudioCapabilities(25360): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(25360): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(25360): Unsupported mime audio/pcm
W/AudioCapabilities(25360): Unsupported mime audio/ra
W/AudioCapabilities(25360): Unsupported mime audio/x-ms-wma
W/VideoCapabilities(25360): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(25360): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(25360): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(25360): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(25360): Unsupported mime video/divx
W/VideoCapabilities(25360): Unsupported mime video/divx3
W/VideoCapabilities(25360): Unsupported mime video/flv1
W/VideoCapabilities(25360): Unsupported mime video/x-flv
W/VideoCapabilities(25360): Unsupported mime video/mjpeg
W/VideoCapabilities(25360): Unsupported mime video/x-motion-jpeg
W/VideoCapabilities(25360): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(25360): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(25360): Unsupported mime video/rv
W/VideoCapabilities(25360): Unsupported mime video/x-ms-wmv
I/chatty  (25360): uid=10173(com.piesat.flutterapp) Chrome_InProcGp identical 1 line
W/VideoCapabilities(25360): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(25360): Unsupported mime video/x-ms-wmv2
W/VideoCapabilities(25360): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(25360): Unrecognized profile 2130706434 for video/avc
I/VideoCapabilities(25360): Unsupported profile 4 for video/mp4v-es
D/NetworkSecurityConfig(25360): No Network Security Config specified, using platform default
I/zygote64(25360): Do partial code cache collection, code=30KB, data=28KB
I/zygote64(25360): After code cache collection, code=30KB, data=28KB
I/zygote64(25360): Increasing code cache capacity to 128KB
I/zygote64(25360): Do partial code cache collection, code=61KB, data=51KB
I/zygote64(25360): After code cache collection, code=61KB, data=51KB
I/zygote64(25360): Increasing code cache capacity to 256KB
I/zygote64(25360): Do full code cache collection, code=117KB, data=100KB
I/zygote64(25360): After code cache collection, code=93KB, data=61KB
I/chromium(25360): [INFO:CONSOLE(166)] "THREE.WebGLRenderer", source: https://ws.runidea.net/webxr/examples/libs/three.min.js (166)
I/CameraManagerGlobal(25360): Connecting to camera service
W/CameraManagerGlobal(25360): [soar.cts] ignore the status update of camera: 2
I/chromium(25360): [INFO:CONSOLE(208)] "could not find the floor anchor", source: https://ws.runidea.net/webxr/examples/common.js (208)
V/Camera  (25360): finalize camera
I/chatty  (25360): uid=10173(com.piesat.flutterapp) FinalizerDaemon identical 1 line
V/Camera  (25360): finalize camera
I/VPM     (25360): getProjectName ro.vivo.product.model=PD1728
W/CameraBase(25360): An error occurred while connecting to camera 1: Status(-8): '1: validateClientPermissionsLocked:1009: Caller
"com.piesat.flutterapp" (PID 10173, UID 25360) cannot open camera "1" without camera permission'
E/cr_VideoCapture(25360): Camera.open: 
E/cr_VideoCapture(25360): java.lang.RuntimeException: Fail to connect to camera service
E/cr_VideoCapture(25360):       at android.hardware.Camera.<init>(Camera.java:812)
E/cr_VideoCapture(25360):       at android.hardware.Camera.open(Camera.java:467)
E/cr_VideoCapture(25360):       at org.chromium.media.VideoCaptureCamera.getDeviceSupportedFormats(VideoCaptureCamera.java:32)
E/cr_VideoCapture(25360):       at org.chromium.media.VideoCaptureFactory.getDeviceSupportedFormats(VideoCaptureFactory.java:31)
E/libc    (25360): Access denied finding property "camera.hal1.packagelist"
W/Thread-4(25360): type=1400 audit(0.0:45262): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12266
scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
W/CameraBase(25360): An error occurred while connecting to camera 0: Status(-8): '1: validateClientPermissionsLocked:1009: Caller
"com.piesat.flutterapp" (PID 10173, UID 25360) cannot open camera "0" without camera permission'
E/cr_VideoCapture(25360): Camera.open: 
E/cr_VideoCapture(25360): java.lang.RuntimeException: Fail to connect to camera service
E/cr_VideoCapture(25360):       at android.hardware.Camera.<init>(Camera.java:812)
E/cr_VideoCapture(25360):       at android.hardware.Camera.open(Camera.java:467)
E/cr_VideoCapture(25360):       at org.chromium.media.VideoCaptureCamera.getDeviceSupportedFormats(VideoCaptureCamera.java:32)
E/cr_VideoCapture(25360):       at org.chromium.media.VideoCaptureFactory.getDeviceSupportedFormats(VideoCaptureFactory.java:31)
W/cr_media(25360): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/chromium(25360): [INFO:CONSOLE(302)] "Could not set up video stream", source:
https://ws.runidea.net/webxr/polyfill/reality/CameraReality.js (302)
I/zygote64(25360): Do partial code cache collection, code=116KB, data=100KB
I/zygote64(25360): After code cache collection, code=116KB, data=100KB
I/zygote64(25360): Increasing code cache capacity to 512KB
I/zygote64(25360): Compiler allocated 8MB to compile void android.view.ViewRootImpl.performTraversals()
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4
D/ViewRootImpl[MainActivity](25360): pokeDrawLockedIfNeeded displayState=4

**Comment by slightfoot** [comment]
This is not this plugin, but the fact you did not request the camera permission as the log above states. Please look into doing that.
