### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by bagintz** [fluttercommunity/flutter_webview_plugin#254]
I see the code has the following at the top of base.dart:

// TODO: use an id by webview to be able to manage multiple webview

Where is that on the roadmap?

Thanks for the great plugin!

Bryan

**Comment by feudadrien** [comment]
@lejard-h  any thoughtts

**Comment by charafau** [comment]
What would be the use case for this? I'd rather stay with single webview, since that's probably the best approach to this plugin. Multiple instances are supported by official plugin, which in the end will be used by everyone
