### ISSUE TITLE
iOS open webview always loading

### ISSUE THREAD

**Issue by MichaelHuyp** [fluttercommunity/flutter_webview_plugin#271]
![image](https://user-images.githubusercontent.com/12581809/49992891-43bc0780-ffc0-11e8-9c44-9caf865c1379.png)

**Comment by jinfagang** [comment]
same issue here........

**Comment by MichaelHuyp** [comment]
when i use Xcode build app , webview always loading. but when i use VS Code Debug App webview Load correctly.

**Comment by jinfagang** [comment]
@MichaelHuyp Does it all in same command which is `flutter run`?

**Comment by firetheworld** [comment]
same issue here
And flutter_webview_plugin:    version: "0.3.0+2"

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.30.1)
[✓] Connected device (2 available)

**Comment by jinfagang** [comment]
@FlutterCommunityBot Does the any fix on this issue? this plugin will not work on iOS if not fix it soon....................

**Comment by hubcarl** [comment]
same issue here........

**Comment by The-five-stooges** [comment]
stuck here

**Comment by charafau** [comment]
you might need to add 

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoadsInWebContent</key>
  <true/>
</dict>
```

if you're using iOS 10 and above or:

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
```

when you need to support iOS 9 

more about it here:

https://blogs.perficient.com/2016/11/28/ats-in-ios-10/
