### ISSUE TITLE
Ability to intercept URL

### ISSUE THREAD

**Issue by SimplyJaymin** [fluttercommunity/flutter_webview_plugin#293]
Hello,
How can I intercept a URL before it is loaded into the webview & stop loading?
I tried the following - 
`_onStateChanged =
        flutterWebviewPlugin.onStateChanged.listen((WebViewStateChanged state) {
      if (state.url.startsWith("someScheme")) {
        flutterWebviewPlugin.stopLoading();
      }
    });`

But the onStateChanged is called after the url has loaded into the webview, so I cannot stop the loading.

**Comment by mohammedmunaf** [comment]
I have the same issue. Pease help!

**Comment by JannieT** [comment]
You can intercept on the onUrlChanged event which fires before the WebViewState.startLoad state change. I am using it like this:

```
webview.onUrlChanged.listen( (String url) async {
    if (!mounted) return;
    
    if (!_isSpecialUrl(url)) return;

    if (await canLaunch(url)) {
      print('diverting: $url');
      webview.stopLoading();
      await launch(url);
    }
    
  });
```

**Comment by mohammedmunaf** [comment]
@JannieT No use. Webview doesn't stop loading. callback come to `onUrlChanged` once the loading already starts, not before loading.

**Comment by JannieT** [comment]
@Mohammed90 works great for me on Flutter v1.2.1, Plugin v0.3.3

This is my event trace:

> flutter: onStateChanged: WebViewState.shouldStart https://redacted.com/notes
> flutter: onUrlChanged: https://redacted.com/notes
> flutter: onStateChanged: WebViewState.startLoad https://redacted.com/notes
> flutter: onHttpError: 200 https://redacted.com/notes
> flutter: onStateChanged: WebViewState.finishLoad https://redacted.com/notes

**Comment by mohammedmunaf** [comment]
@JannieT I am also using Plugin v0.3.3 but flutter 1.0.0+1 
Below is my console log. <onUrlChanged> is called after <WebViewState.startLoad>

 I/flutter (21612): WebViewState.shouldStart
I/flutter (21612): WebViewState.startLoad
I/flutter (21612): onUrlChanged
I/flutter (21612): WebViewState.finishLoad

**Comment by JannieT** [comment]
@mohammedmunaf have you tried intercepting at WebViewState.shouldStart?

**Comment by mohammedmunaf** [comment]
Finally this worked for me! Happy coding 👍 

```
flutterWebviewPlugin.onStateChanged.listen((WebViewStateChanged state) async {
      if (state.type==WebViewState.shouldStart){
         if(state.url.startsWith('https://www.google.com')){
            flutterWebviewPlugin.stopLoading();
          } 
      }
    });
```
