### ISSUE TITLE
Statusbar overlapping in webview

### ISSUE THREAD

**Issue by UwaisWisitech** [fluttercommunity/flutter_webview_plugin#296]
I have integrated web view in my flutter App but status bar overlapping the web view .

![git](https://user-images.githubusercontent.com/46367241/51104998-ba416480-180d-11e9-8a50-478d6690a506.png)

**Comment by UwaisWisitech** [comment]
Here is my code

    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Container(
        margin: const EdgeInsets.only(top: 0.0),
        child: SafeArea(
          top: false,
          child: new WebviewScaffold(
              url: selectedUrl,
              withZoom: true,
              withLocalStorage: true,
              hidden: true,
            initialChild: Container(
              color: Colors.white,
              child: const Center(
                child: Text('Waiting.....'),
              ),
            ),
          ),
        ),
      )

    ,
    );

**Comment by sameerbakre** [comment]
There is no direct way to handle it. You have two options here. Either add appBar and everything would be taken care by itself. Or other option is little bit dirty coding. Once your page is loaded call following

flutterWebviewPlugin.resize(_buildRect()) 

  Rect _buildRect() {
    final topPadding = mediaQuery.padding.top;
    final top = topPadding;

    var height = mediaQuery.size.height - top;
    height -= 56.0 + mediaQuery.padding.bottom;
    if (height < 0.0) {
      height = 0.0;
    }

    return new Rect.fromLTWH(0.0, top, mediaQuery.size.width, height);
  }

**Comment by iontichy123** [comment]
Sorry, for newbee question. How/where to initialize this medioQuery member?

**Comment by iontichy123** [comment]
Found another solution, instead of AppBar I've used this:

appBar: PreferredSize( 
                child: Container(),
                preferredSize: Size.fromHeight(0.0),
              )

**Comment by baoxiehao** [comment]
> initialChild

Not working for me

**Comment by baoxiehao** [comment]
> Here is my code
> 
> ```
> return new MaterialApp(
>   debugShowCheckedModeBanner: false,
>   home: Container(
>     margin: const EdgeInsets.only(top: 0.0),
>     child: SafeArea(
>       top: false,
>       child: new WebviewScaffold(
>           url: selectedUrl,
>           withZoom: true,
>           withLocalStorage: true,
>           hidden: true,
>         initialChild: Container(
>           color: Colors.white,
>           child: const Center(
>             child: Text('Waiting.....'),
>           ),
>         ),
>       ),
>     ),
>   )
> 
> ,
> );
> ```

It does not work for me.

**Comment by charafau** [comment]
@sameerbakre  already answered this question either use AppBar or use rect constructor to resize webview, coping for everyone:

```dart
futterWebviewPlugin.resize(_buildRect())

Rect _buildRect() {
   final topPadding = mediaQuery.padding.top;
   final top = topPadding;
   var height = mediaQuery.size.height - top;
   height -= 56.0 + mediaQuery.padding.bottom;

   if (height < 0.0) {
      height = 0.0;
   }

   return new Rect.fromLTWH(0.0, top, mediaQuery.size.width, height);
}
```
