### ISSUE TITLE
How to set local variable to post message whenever a new one is listened

### ISSUE THREAD

**Issue by erdemyerebasmaz** [fluttercommunity/flutter_webview_plugin#305]
Hello,

I can listen to post messages on browser like this but how I didn't quite understand how I can set a local variable to _event.data_.
```
String script1 = 'window.addEventListener("message", receiveMessage, false);' +
                'function receiveMessage(event) {console.log(event.data);}';
widgetWebview.evalJavascript(script);
```
I tried
```
String script2 = 'var test = "Hello, World!";'+
                 'function getMessage(val) {return val;}' +
                 'getMessage(test);';
var testLocal = await widgetWebview.evalJavascript(script2);
```
and you can set _testLocal_ to _test_ but I couldn't apply it to post message. 

Also, I tried setting value of _test_ inside _script1_ and trigger onUrlChanged inside receiveMessage function and access it from _script2_. The variables in _script1_ were not accessible by _script2_. 

Can we use a callback function to communicate between app & webview?

Thanks

**Comment by erdemyerebasmaz** [comment]
This is how I solved this issue:

initState() of my Flutter class where I'm using the webview widget.
```
...
widgetWebview.testStream.listen((value) {

      });
    });
    widgetWebview.onStateChanged.listen((state) async {
      if (state.type == WebViewState.finishLoad) {
        String script = 'window.addEventListener("message", receiveMessage, false);' +
            'function receiveMessage(event) {FlutterJsInterface.getPostMessage(event.data);}';
        widgetWebview.evalJavascript(script);
      }
    });
...
```

Added this under WebviewManager's constructor:
`webView.addJavascriptInterface(new FlutterJsInterface(), "FlutterJsInterface");`
Second parameter is how it will be referenced inside javascript code.

and this inside WebviewManager.

public class FlutterJsInterface {
    @JavascriptInterface
    public void getPostMessage(String value){
        Map<String, Object> map= new HashMap<>();
        map.put("postMessage",value);
        FlutterWebviewPlugin.channel.invokeMethod("test", map);
    }
}

and created a stream inside base.dart

`final _testStream = StreamController<String>.broadcast();`

and added 'test' case under _handleMessages

```
case 'test':
        _testStream.add(call.arguments['postMessage']);
        break;
```

You can change the type, parse string to json object on both ends etc. Hope this was helpful.

**Comment by erdemyerebasmaz** [comment]
[Changes can be seen here](https://github.com/erdemyerebasmaz/flutter_webview_plugin/commit/59a4c33751d5ce71341e2e4b720c9f1553d01f8c)

**Comment by Wirehome** [comment]
Where is the WebviewManager?

**Comment by wackyapps** [comment]
I have updated the code changes in the source files. How do build this now to apply in compiled plugin.

**Comment by erdemyerebasmaz** [comment]
> I have updated the code changes in the source files. How do build this now to apply in compiled plugin.

@wackyapps 
If you upgrade plugins of your project and there was a change in the plugin that references it's own repo, your changes will be overridden.
That's why you fork the plugin, apply the changes and reference that repo in your projects pubspec.yaml such as:
```
flutter_webview_plugin:
    git:
      url: https://github.com/your_repo_name/flutter_webview_plugin.git
```
