### ISSUE TITLE
how to send message from javacript to flutter?

### ISSUE THREAD

**Issue by littlesalt** [fluttercommunity/flutter_webview_plugin#309]
I want to send message from js to flutter .I try using wondow.postMessage to send message to flutter,but it fail.

**Comment by erdemyerebasmaz** [comment]
https://github.com/erdemyerebasmaz/flutter_webview_plugin/commit/59a4c33751d5ce71341e2e4b720c9f1553d01f8c

**Comment by littlesalt** [comment]
it is not work !
============
js code:
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
</head>

<body>
	<div id="time"></div>
	<div id="message"></div>
	
	<input id="dd" style="width:160px;" placeholder="请输入要向flutter发送的内容"></input><br/><br/>
	<button id="button" style="background-color:#158461;height:30px;">发送数据到flutter</button>
	
</body>

<script>

	 function sendData(data) {
	window.postMessage(data, '*');
	}
  window.onload = function () {
	  
	    document.getElementById('button').onclick = function () {
	      sendData(document.getElementById('dd').value);
	    }
	  }
</script>
</html>
===================
flutter code:
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

class WebviewDemo extends StatefulWidget{
  @override
  _WebviewDemoState createState() =>_WebviewDemoState();

}

class _WebviewDemoState extends State<WebviewDemo>{
  final flutterWebviewPlugin = new FlutterWebviewPlugin();


  @override
  void initState() {
    super.initState();
    flutterWebviewPlugin.close();
    flutterWebviewPlugin.lightningLinkStream.listen((message){
      print(message);
    });

  }


  @override
  void dispose() {
    flutterWebviewPlugin.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(url: 'http://192.168.3.100:8080/index7.html');
  }

}

**Comment by erdemyerebasmaz** [comment]
It's hard to read your comment, please format it with code tags.
I think you are sending post message but haven't set a event listener to listen to those messages.

**Comment by littlesalt** [comment]
@erdemyerebasmaz  thanks .I have formated my code.

**Comment by littlesalt** [comment]
@erdemyerebasmaz I want to received message by flutter.

**Comment by erdemyerebasmaz** [comment]
You need to fork and make changes on the plugin. I've added a javascript interface and passed the listened value to a stream that can be listened inside flutter.
I've shown the minimum changes [here].(https://github.com/erdemyerebasmaz/flutter_webview_plugin/commit/59a4c33751d5ce71341e2e4b720c9f1553d01f8c)

Adjust and rename the methods according to your needs.

**Comment by littlesalt** [comment]
I used your branch,and alse add `flutterWebviewPlugin .onStateChanged.listen((state) async {...`

**Comment by erdemyerebasmaz** [comment]
Okay, if you are using my branch without any changes just add this to your initState();
```
    flutterWebviewPlugin.onStateChanged.listen((state) async {
      if (state.type == WebViewState.finishLoad) {
        String script =
            'window.addEventListener("message", receiveMessage, false);' +
                'function receiveMessage(event) {Android.getPostMessage(event.data);}';
        flutterWebviewPlugin.evalJavascript(script);
      }
    });
```

Try hiding instead of closing the flutterWebviewPlugin.

**Comment by littlesalt** [comment]
@erdemyerebasmaz Tell you good news,I have resolved this problem through your help!  Thank you very much!

**Comment by Spicely** [comment]
@littlesalt ios  How to solve

**Comment by SakinaBoriwala21** [comment]
@erdemyerebasmaz Hey, thanks a lot for this. I have a button on the page that I am loading. I am calling an onClick() event that does this: 

`
<div onclick=" MobileApp.postMessage('open_form'); "></div>`

I added this to my initState():

`  @override
  void initState() {
    super.initState();
    flutterWebviewPlugin.onStateChanged.listen((state) async {
      if (state.type == WebViewState.finishLoad) {
        String script =
            'window.addEventListener("MobileApp", receiveMessage, false);' +
                'function receiveMessage(event) {Android.getPostMessage(event.data);}';
        flutterWebviewPlugin.evalJavascript(script);
      }
    });
    flutterWebviewPlugin.close();
    flutterWebviewPlugin.lightningLinkStream.listen((message) {
      print(message);
    });
  }`

But I get this error whenever I tap on the button:

 "Uncaught ReferenceError: MobileApp is not defined", source: $url (371)

I want to call a function whenever the button is tapped. Please help me if possible, it's really urgent.

**Comment by SakinaBoriwala21** [comment]
`@override void initState() { super.initState(); flutterWebviewPlugin.onStateChanged.listen((state) async { if (state.type == WebViewState.finishLoad) { String script = 'window.addEventListener("MobileApp", receiveMessage, false);' + 'function receiveMessage(event) {Android.getPostMessage(event.data);}'; flutterWebviewPlugin.evalJavascript(script); } }); flutterWebviewPlugin.close(); flutterWebviewPlugin.lightningLinkStream.listen((message) { print(message); }); }`

**Comment by Wirehome** [comment]
Where is webView.addJavascriptInterface and WebAppInterface?

**Comment by heinzan** [comment]
How listen Javascript function from backend to flutter

**Comment by erdemyerebasmaz** [comment]
> Where is webView.addJavascriptInterface and WebAppInterface?

You add it under WebviewManager.java See this [commit](https://github.com/erdemyerebasmaz/flutter_webview_plugin/commit/59a4c33751d5ce71341e2e4b720c9f1553d01f8c)

**Comment by erdemyerebasmaz** [comment]
> How listen Javascript function from backend to flutter
@heinzan 

I'm not sure what you mean but to listen post messages from a webview and listen it on Flutter, check [this](https://github.com/fluttercommunity/flutter_webview_plugin/issues/309#issuecomment-457956130)

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz Hey, thanks a lot for this. I have a button on the page that I am loading. I am calling an onClick() event that does this:
> 
> `button onclick=" MobileApp.postMessage('open_form'); "`
> 
> I added this to my initState():
> 
> ```
>   void initState() {
>     super.initState();
>     flutterWebviewPlugin.onStateChanged.listen((state) async {
>       if (state.type == WebViewState.finishLoad) {
>         String script =
>             'MobileApp.addEventListener("message", receiveMessage, false);' +
>                 'function receiveMessage(event) {Android.getPostMessage(event.data);}';
>         flutterWebviewPlugin.evalJavascript(script);
>       }
>     });
>     flutterWebviewPlugin.close();
>     flutterWebviewPlugin.lightningLinkStream.listen((message) {
>       print(message);
>     });
>   }```
> 
> But I get this error whenever I tap on the button:
> 
>  "Uncaught ReferenceError: MobileApp is not defined", source: $url (371)
> ```
> I want to call a function whenever the button is tapped. Please help me if possible, it's really urgent.
> 
> @littlesalt @erdemyerebasmaz I know I am doing something wrong in my JS Script. If possible, please guide me.
> 

As it says, the browser object model named MobileApp is not defined. See [here](https://www.w3schools.com/js/js_window.asp). Try using window instead.

 - onclick="_window_.postMessage('open_form');" ....
 - String script = '_window_.addEventListener ....

**Comment by sakina1403** [comment]
> > @erdemyerebasmaz Hey, thanks a lot for this. I have a button on the page that I am loading. I am calling an onClick() event that does this:
> > `button onclick=" MobileApp.postMessage('open_form'); "`
> > I added this to my initState():
> > ```
> >   void initState() {
> >     super.initState();
> >     flutterWebviewPlugin.onStateChanged.listen((state) async {
> >       if (state.type == WebViewState.finishLoad) {
> >         String script =
> >             'MobileApp.addEventListener("message", receiveMessage, false);' +
> >                 'function receiveMessage(event) {Android.getPostMessage(event.data);}';
> >         flutterWebviewPlugin.evalJavascript(script);
> >       }
> >     });
> >     flutterWebviewPlugin.close();
> >     flutterWebviewPlugin.lightningLinkStream.listen((message) {
> >       print(message);
> >     });
> >   }```
> > 
> > But I get this error whenever I tap on the button:
> > 
> >  "Uncaught ReferenceError: MobileApp is not defined", source: $url (371)
> > ```
> > 
> > 
> > I want to call a function whenever the button is tapped. Please help me if possible, it's really urgent.
> > @littlesalt @erdemyerebasmaz I know I am doing something wrong in my JS Script. If possible, please guide me.
> 
> As it says, the browser object model named MobileApp is not defined. See [here](https://www.w3schools.com/js/js_window.asp). Try using window instead.
> 
> * onclick="_window_.postMessage('open_form');" ....
> * String script = '_window_.addEventListener ....

@erdemyerebasmaz Thanks for getting back to me. Earlier I was using webview_flutter but it doesn't open webviews so I am trying to switch back to this.

webview_flutter provides javascript channels property and that's how I used to listen to postMessages.

But now, I don't know how to listen to these messages with flutter_webview_plugin or atleast avoid the error that says  `"Uncaught ReferenceError: MobileApp is not defined"`, source: $url (371) so that the rest of the JS can load and work properly.

```
 JavascriptChannel _toasterJavascriptChannel9(BuildContext context) {
    return JavascriptChannel(
      name: 'MobileApp',
      onMessageReceived: (JavascriptMessage message) {
        print('Message received');
        ''');
      },
    );
  }
```

**Comment by OPY-bbt** [comment]
I solved this problem in iOS and Android, I hope it's helpful。https://github.com/fluttercommunity/flutter_webview_plugin/pull/457

**Comment by varunkumarmedam** [comment]
Can You guys provide complete flutter and js code for better understanding...
