### ISSUE TITLE
hide loadingprogressbar in the center

### ISSUE THREAD

**Issue by moonljt521** [fluttercommunity/flutter_webview_plugin#311]
how to hide loadingprogressbar in the center ，because I want to use a style myself

**Comment by hebersousa** [comment]
if you are using WebviewScaffold:
WebviewScaffold(
        url: 'https://www.google.com'
        initialChild: Container(
                child:  Center(child: Text('Waiting.....')),
            ),
   )

**Comment by moonljt521** [comment]
thanks

**Comment by moonljt521** [comment]
thanks @hebersousa
