### ISSUE TITLE
Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by Stephan-Enoro** [fluttercommunity/flutter_webview_plugin#314]
Hi
I have used flutter_webview_plugin: ^0.3.0+2 for a while with success.
Suddenly it did not work. 
I created an empty flutter project and included flutter_webview_plugin.
Same thing after a Package get:

**Could not find a file named "pubspec.yaml" in "/Users/stephan/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.0+2"**

Very strange. First time I have seen this error message.

Environment:
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (10 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by Stephan-Enoro** [comment]
But ^0.2.1+2 works fine

**Comment by lanxuexing** [comment]
rm ./flutter/.pub-cache/git    @Stephan-Enoro

**Comment by charafau** [comment]
as stated above, try to remove your cache. Closing for now, will reopen when needed.
