### ISSUE TITLE
Is flutter_webview_plugin ^0.3.0+2 developed with Flutter Stable branch?

### ISSUE THREAD

**Issue by Stephan-Enoro** [fluttercommunity/flutter_webview_plugin#319]
Hi 

We have still problem with ^0.3.0+2

1. New flutter installation.
2. Flutter upgrade, see below
3. Flutter doctor: All set
3. New Flutter app template with one new dependency: **flutter_webview_plugin: ^0.3.0+2** 
4. Package get
5. Error: 
Could not find a file named "pubspec.yaml" in "/......./Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.0+2".

Have seen this with other plugins. After switching to a previous version and then back it sometimes works. Invalidate Cashes / Restart doesn't help

0.2.1+2 . works just fine. You may ask: why not use that version and be happy and go on?
The answer is that we are planning to migrate a two large apps (Android and iOS) to one Flutter app.
We have identified all type requirements and building a Flutter test app in order to validate if we have nerves to make the migration. So far it looks very good. 

For us it is important (critical) to know how stable different plugins are before we start the development and finally go live.
 I read somewhere that many plugin developer use Flutter development branches in order to use the latest version.

**Is flutter_webview_plugin ^0.3.0+2 developed with Flutter Stable branch?**

If that is not the case.  How can we know which plugin version is recommended for a certain Flutter Stable version? We are perfectly happy to wait with the latest features. Stability is the key word here.

Thanks in advanced for any information.
Stephan

Flutter upgrade output:
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by Stephan-Enoro** [comment]
Sorry for the trouble
After removing flutter_webview_plugin: ^0.3.0+2 from the .pub-cache and a new Package get it works like a charm. What a relief :-) Now back to business.

**Comment by ParthipanThangaraju** [comment]
How did you removed the error @Stephan-Enoro . Where is the .pub-cache? I having this issue. please help me

**Comment by charafau** [comment]
@ParthipanThangaraju  in your $HOME directory

**Comment by Stephan-Enoro** [comment]
Sorry a bit late. 

pub-cache is a storage where all packages are stored. All Flutter project use the pub-cache.
What I did was just deleting the package folder in the cache and get a fresh package back
flutter/.pub-cache/hosted/pub.dartlang.org/**package-123**

On mac the .pub-cache folder is hidden so you have to make it visible 
https://setapp.com/how-to/show-hidden-files-on-mac
