### ISSUE TITLE
headers propagation to subrequest

### ISSUE THREAD

**Issue by macnal** [fluttercommunity/flutter_webview_plugin#321]
If I set up headers in request and than a page gets others resources such as css, js,... the headers in not attaching to this requests. Is there a way to solve this problem?

**Comment by macnal** [comment]
I mean for example authorization header that is not passed to resources like java script files

**Comment by MrDragonn** [comment]
hello  how do you resolve this question？

**Comment by irineusturza** [comment]
same problem here @macnal . how did you fix it? tks!

**Comment by shubhanshusingh** [comment]
@macnal did anyone solve this?
