### ISSUE TITLE
is there a function for webView.canGoBack

### ISSUE THREAD

**Issue by moonljt521** [fluttercommunity/flutter_webview_plugin#324]
I want to override my backBtn of toobar , I need judge the webview has last stack record ，I will close the page if there is not，
is there a function for webView.canGoBack，please 。。。

**Comment by huuang** [comment]
I wonder why there is no `canGoBack` function, but has `goBack` function

**Comment by apm29** [comment]
need this function

**Comment by charafau** [comment]
https://github.com/fluttercommunity/flutter_webview_plugin/issues/432
