### ISSUE TITLE
Can Webview be Transparent?

### ISSUE THREAD

**Issue by mlanteigne** [fluttercommunity/flutter_webview_plugin#335]
Hi, I would like to set the webview to have transparent background so I could show what's behind.
Is it possible?, thanks!

**Comment by mlanteigne** [comment]
If anyone is wondering, you need to set webView.setBackgroundColor(0); inside the WebviewManager.java

**Comment by IonelLupu** [comment]
@mlanteigne why did you close this?

**Comment by rivetingpeppermint** [comment]
@mlanteigne Where should I put this line of code? I tried the Webview is covered by the initialChild widget now. Is that what's supposed to happen?
