### ISSUE TITLE
Won't load on release

### ISSUE THREAD

**Issue by bagintz** [fluttercommunity/flutter_webview_plugin#339]
For some reason when I do a simple flutterWebviewPlugin.launch for release it does not work, but a regular build (debug) does.  I am sure I am missing something simple.  Any ideas?

**Comment by hyvikk** [comment]
I have same issue.

**Comment by charafau** [comment]
Can you please give more info? Plugin version, Android / iOS / both, error log if possible.

**Comment by charafau** [comment]
also, might be related to this one ? https://github.com/fluttercommunity/flutter_webview_plugin/issues/239

**Comment by harsha973** [comment]
@charafau ,

I'm facing the same issue in my project. For demo, created a basic sample to load "https://google.co.nz". Git sample [here](https://github.com/harsha973/flutter_webview_pliugin_sample).

 It works perfectly in debug mode. With release APK, Webview cant load the url. Please find the screen shot below.

![Screenshot_20190418-091524](https://user-images.githubusercontent.com/1115535/56321524-fe505680-61ba-11e9-8bab-7c6ab4de93d2.png)

Flutter doctor here

```[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-AU)
    • Flutter version 1.2.1 at /Users/sree/Work/Installation/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sree/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sree/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Pixel 3 • 89TX0FYE3 • android-arm64 • Android Q (API 28)

````

I think I'm missing something real small info.  Any leads please?

And this on **not** related to #239.

**Comment by liguande** [comment]
I have same issue too.

**Comment by liguande** [comment]
it workes in profile mode

**Comment by harsha973** [comment]
Anyone got a working solution?

**Comment by harsha973** [comment]
**FIXED**

It's a small permission issue on Android. Added `<uses-permission android:name="android.permission.INTERNET"/>` to AndroidManifest.xml and webview loads url 🎉 

For reference, I have a basic Git sample [here](https://github.com/harsha973/flutter_webview_pliugin_sample)

But not sure why it works in debug mode though 🤔

**Comment by charafau** [comment]
Sorry I was out for some time. Yes.. you need to have Internet permission - it's added by default in debug mode (that's why you can hot reload code) but seems like it's stripped on release mode. Closing this one!

**Comment by Maulik009** [comment]
No its still gives me error while generating apk from release mode.

**Comment by charafau** [comment]
@Maulik009  need more info, some logs, code..

**Comment by MahiMahionly** [comment]
get the Release APK from this command in terminal: ** flutter run --release **.
This Will Definitely Solve Your All Those Problems..
Also It have less MB output than Getting Release Apk from Build ->Flutter->Build Apk ...etc .
:)Mahi
