### ISSUE TITLE
Flutter widget on top of webview

### ISSUE THREAD

**Issue by Sarthaktydy** [fluttercommunity/flutter_webview_plugin#343]
This is a feature that is missing when you're in the Webview you can't make a widget appear on top of it. please add this feature.

**Comment by SakinaBoriwala21** [comment]
Yes, please. I want to add a back button which is common throughout the App, but I am unable to place it on WebView.

I am using the WebView as a part of Stack.

```
Stack(
        children: <Widget>[
              WebView(initialUrl: widget.url,),
              WebviewScaffold(
                url: widget.url,
                headers: getHeaders(),
              ),
              AppBackButton(
                onWillPop: () {
                  Navigator.pop(context);
                },
              ),
            ],
          )
```
But I am not able to view this button over WebView :-1:

**Comment by Yodart** [comment]
Any updates?

**Comment by Sarthaktydy** [comment]
No updates but you can try flutter_webview instead, although there are some limitation to that webview also, it doesn't support calling storage for uploading document (My project on angular needs that).

**Comment by Sarthaktydy** [comment]
> Yes, please. I want to add a back button which is common throughout the App, but I am unable to place it on WebView.
> 
> I am using the WebView as a part of Stack.
> 
> ```
> Stack(
>         children: <Widget>[
>               WebView(initialUrl: widget.url,),
>               WebviewScaffold(
>                 url: widget.url,
>                 headers: getHeaders(),
>               ),
>               AppBackButton(
>                 onWillPop: () {
>                   Navigator.pop(context);
>                 },
>               ),
>             ],
>           )
> ```
> But I am not able to view this button over WebView 👎

if you only want this functionality there is two way to do it, either make a close button on appbar or switch to the flutter_webview. I mentioned limitation of flutter_webview above.

**Comment by SakinaBoriwala21** [comment]
> > Yes, please. I want to add a back button which is common throughout the App, but I am unable to place it on WebView.
> > I am using the WebView as a part of Stack.
> > ```
> > Stack(
> >         children: <Widget>[
> >               WebView(initialUrl: widget.url,),
> >               WebviewScaffold(
> >                 url: widget.url,
> >                 headers: getHeaders(),
> >               ),
> >               AppBackButton(
> >                 onWillPop: () {
> >                   Navigator.pop(context);
> >                 },
> >               ),
> >             ],
> >           )
> > ```
> > But I am not able to view this button over WebView -1
> 
> if you only want this functionality there is two way to do it, either make a close button on appbar or switch to the flutter_webview. I mentioned limitation of flutter_webview above.

I did make the close button on AppBar, but unfortunately the client doesn't find it user friendly because of the bar. Also, flutter_webview will not allow me to send headers, and that's really important to me, infact the main reason why I switched to this plugin.

**Comment by SakinaBoriwala21** [comment]
@Sarthaktydy I did make the close button on AppBar, but unfortunately the client doesn't find it user friendly because of the bar. Also, flutter_webview will not allow me to send headers, and that's really important to me, infact the main reason why I switched to this plugin.

**Comment by Sarthaktydy** [comment]
> @Sarthaktydy I did make the close button on AppBar, but unfortunately the client doesn't find it user friendly because of the bar. Also, flutter_webview will not allow me to send headers, and that's really important to me, infact the main reason why I switched to this plugin.

Yeah ,so thing is I'm also stuck with my project since both of the webview has limitation, all we can do is raise issue on both of the webview and wait them to fix it or else creating whole thing into the flutter and ditch webview :(. I wrote multiple emails to webview_flutter developer team but no luck. try mailing them with issue you're facing along side the issue link.

also refer:-
#30549

**Comment by Sarthaktydy** [comment]
> @Sarthaktydy I did make the close button on AppBar, but unfortunately the client doesn't find it user friendly because of the bar. Also, flutter_webview will not allow me to send headers, and that's really important to me, infact the main reason why I switched to this plugin.

They've added header in last update try webview_flutter now. :)

**Comment by SakinaBoriwala21** [comment]
@Sarthaktydy Ohh that's great news!! I will check it out!

**Comment by Skyyo** [comment]
@Sarthaktydy found a way to do it using Scaffold's FAB.
```
Scaffold(
      floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      floatingActionButton:  GestureDetector(
        child: Container(
          margin: EdgeInsets.only(top: calculateInsetsAndDesiredMarginHere(), left : sameForLeftSide())
          child: Icon(Icons.clear, color: Colors.black),
        ),
        onTap: ( ) => Navigator.pop(context),
      ),
     body: "your webview"
```

**Comment by charafau** [comment]
This is probably out of scope of this project. We would like to provide basic webview functionality while official webview plugin is not ready.

**Comment by zhangxinagjunHJH** [comment]
Same problem, can solve the problem now?

**Comment by ahmed-foulad20** [comment]
same problem

**Comment by mcmc2014** [comment]
same problem

**Comment by tejpalSinghRathore** [comment]
same

**Comment by Alaa-Shaker** [comment]
> Yes, please. I want to add a back button which is common throughout the App, but I am unable to place it on WebView.
> 
> I am using the WebView as a part of Stack.
> 
> ```
> Stack(
>         children: <Widget>[
>               WebView(initialUrl: widget.url,),
>               WebviewScaffold(
>                 url: widget.url,
>                 headers: getHeaders(),
>               ),
>               AppBackButton(
>                 onWillPop: () {
>                   Navigator.pop(context);
>                 },
>               ),
>             ],
>           )
> ```
> 
> But I am not able to view this button over WebView 👎

I think you can use webviewx instead webview and put the button on WebViewAware , this solution in the Documentation (https://pub.dev/packages/webviewx)

**Comment by Binozo** [comment]
still same problem
