### ISSUE TITLE
How to have custom page load instead of "Web Page not available" in case of no internet connection

### ISSUE THREAD

**Issue by amankataria** [fluttercommunity/flutter_webview_plugin#348]
I want the application to look as authentic as possible. So I want a custom page or just my website loaded (offline version, like its in google chrome mobile)

**Comment by cTatu** [comment]
You could use [this ](https://pub.dartlang.org/packages/connectivity) package to check if there is an available connection and if it's not you could lauch the webview with a static page.

**Comment by amankataria** [comment]
@cTatu 

I am trying to launch a custom static html page instead of my URL(my website 'wwww.duevents.in') if there is no internet connection, since the "Web Page not available" page doesn't look very professional.

I am using this to check the internet on the device and it is working fine ('connectionStatus ==true' when the internet is connected and vice versa):

```
Future check() async {
try {
  final result = await InternetAddress.lookup('google.com');
  if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
    connectionStatus = true;
    print("connected $connectionStatus");
  }
} on SocketException catch (_) {
  connectionStatus = false;
  print("not connected $connectionStatus");
}
}
```

This is the code where I have alternate URLs to load if there is no internet connection:

```
WebviewScaffold(      
  url: connectionStatus == true ?"http://www.duevents.in" : Uri.dataFromString('<html><body>hello world</body></html>', mimeType: 'text/html').toString())
```
**Somehow it always shows me the HTML Page with this code no matter if the device has an internet connection or not. Please tell me what is wrong here.**


Link to issue first reported:
https://stackoverflow.com/questions/55283231/flutter-how-to-launch-static-html-page-instead-of-url-if-there-is-no-internet

**Comment by cTatu** [comment]
It's showing the `Uri.dataFromstring...` part always? That's so weird, the ternary operator should evaluate always true and show the `duevents.in` site. You tried to swap the ternary operator by a function that returns one page or another if there is available connection? Maybe the operator is somehow glitched. 
Also check that the syntx is correct, `<condition> ? <action if true> : <action if false>`

**Comment by cTatu** [comment]
The only thing that I could think of is that the `check()` method is running asynchronous so the changes in the `connectionStatus` variable are made after the WebviewScaffold checking for the url.

**Comment by amankataria** [comment]
@cTatu Thanks a lot for your help. This would not have been possible without you. Btw, the issue of  only the html page loading was solved using a FutureBuilder.
Here is the link to solution: https://stackoverflow.com/questions/55283231/flutter-how-to-launch-static-html-page-instead-of-url-if-there-is-no-internet
