### ISSUE TITLE
No named parameter with the name 'resizeToAvoidBottomInset

### ISSUE THREAD

**Issue by CatEatFishs** [fluttercommunity/flutter_webview_plugin#354]
file:///C:/Users/10024/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.1/lib/src/webview_scaffold.dart:106:7:
 Error: No named parameter with the name 'resizeToAvoidBottomInset'.
      resizeToAvoidBottomInset: false,
打包报这个错误，无法打包

Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
 Android Studio (version 3.1)

**Comment by xiaoxiaohaozai** [comment]
升级到最新版 flutter sdk  我是这样解决的

**Comment by kisstank** [comment]
Thanks, had this issue too and @xiaoxiaohaozai s solution ("upgrade to latest version of flutter sdk", for us non chinese speaking and unwilling to use google translate) worked great for me.

**Comment by WK726** [comment]
@xiaoxiaohaozai  Thanks,It s work for me

**Comment by charafau** [comment]
thank you @kisstank , closing.
