### ISSUE TITLE
socketexception: Failed to create server socket (OS Error: The shared flag to bind()...

### ISSUE THREAD

**Issue by arefay** [fluttercommunity/flutter_webview_plugin#355]
I'm getting the following error when launching a url using the flutter web view plugin in my iOS emulator:

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = 127.0.0.1, port = 8585

however, this works fine on android emulator. I'm not entirely sure its related to the plugin or something else related to creating /binding to a server via:

  HttpServer server =
        await HttpServer.bind(InternetAddress.loopbackIPv4, 8585);

again, strangely this works just fine on Android Emulator

**Comment by charafau** [comment]
This is not plugin related, it's some ios security issue when creating local server. I'd suggest to post question on SO if you cannot find answer for that. 

Closing
