### ISSUE TITLE
Getting erro with 0.3.3 "no named parameter with name 'resizeToAvoidBottomInset'"

### ISSUE THREAD

**Issue by far11ven** [fluttercommunity/flutter_webview_plugin#374]
I've included 'flutter_webview_plugin:^0.3.3' in my app.
My app launches with following error screen:
![8e57a030-34fe-4f7b-8cce-eed332a0022d](https://user-images.githubusercontent.com/26922130/55747981-202f3800-5a5b-11e9-99a5-fe4b05cc0f7f.jpg)

**Comment by charafau** [comment]
Hello, thank you for reporting this issue, I checked it, but it works for me - at least in example repo when I put `resizeToAvoidBottomInset: true,` into the `WebviewScaffold` . 


Are you updating this dependency? If so, try to remove `.pub-cache` directory and download project dependencies again.

**Comment by far11ven** [comment]
I tried doing that, but still same happened, ultimately I switched to "webview_flutter". Thanks Though.

**Comment by charafau** [comment]
I'm closing this one. I checked also on new project and it's working. If this re-occurs, please comment in this one.

**Comment by timrijckaert** [comment]
Same issue here.
![Screenshot_1555317995](https://user-images.githubusercontent.com/6739443/56119098-b5569300-5f6b-11e9-877d-1ea435cfe1ae.png)

**Comment by timrijckaert** [comment]
Ok.
It seems like issue nr #354 is related.
I upgraded to the latest Flutter release and it automagically works again.
