### ISSUE TITLE
The webview always cover the dialog

### ISSUE THREAD

**Issue by MengLeiGitHub** [fluttercommunity/flutter_webview_plugin#377]

**Comment by garbirel** [comment]
same

**Comment by charafau** [comment]
what dialog are we talking about? Flutter dialog?

**Comment by MengLeiGitHub** [comment]
> what dialog are we talking about? Flutter dialog?

 Flutter dialog,

**Comment by fantasy525** [comment]
may be，webview must be positioned above the flutterview


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by NewITCorp** [comment]
I use alertdialog with this plugin, results to my webview grayed out but no dialog appears.
if you mean this problem so yes, i have it too...

anyone has a workaround or so?

**Comment by LuyuchengSTAR** [comment]
Warning: The webview is not integrated in the widget tree, it is a native view on top of the flutter view. you won't be able to use snackbars, dialogs ...flutter widget，maybe you can use them after make the webview hidden.

**Comment by charafau** [comment]
As @lycstar  says. It's native view on top of flutter, so due to those limitations it's not possible to use snackbars. Check if official webview plugin works for you and use it if you need snackbars.

**Comment by devmanmath** [comment]
Unable to click alert dialog over webview.

**Comment by lycstar** [comment]
> Unable to click alert dialog over webview.

this repo in outdate, please use webview_flutter
