### ISSUE TITLE
Android keyboard entrance does not resize webview size (from version 0.3.1)

### ISSUE THREAD

**Issue by jameshp** [fluttercommunity/flutter_webview_plugin#379]
I have a web page with a text input field. 
From package Version 0.3.1 onwards, the webview sizes does not change when the keyboard is entered. This leads to the fact that the textinput field is hidden behind the keyboard. 

In Version 0.3.0+2 this works fine. 
Select text input field, keyboard is shown, webview is resized to visible area and text input box stays visible. This is the standard android behavior I know.

In 0.3.1  a change "Fix height of keyboard" was introduced, which might be the reason?  

**0.3.0+2 version (working)**

![screenshot-1554898203582](https://user-images.githubusercontent.com/3824083/55877618-cdf53080-5b9a-11e9-920e-5b27037a76da.jpg)

![screenshot-1554898210900](https://user-images.githubusercontent.com/3824083/55877717-1280cc00-5b9b-11e9-968f-56611e78647e.jpg)

**0.3.1 version (not working)**

![screenshot-1554898263735](https://user-images.githubusercontent.com/3824083/55877645-e1080080-5b9a-11e9-9a35-53eddebc2783.jpg)

![image](https://user-images.githubusercontent.com/3824083/55877597-bc138d80-5b9a-11e9-9b9f-e70c027c1e90.png)

**Comment by jameshp** [comment]
I have double checked and the changed behavior comes from: https://github.com/fluttercommunity/flutter_webview_plugin/pull/272 

the setting: "resizeToAvoidbottomInset" keeps or changes depending on the flag the size if a keyboard is shown.  Now it is always false on the WebviewScaffold Widget and therefore not resizing on keyboard inputs.

**Comment by charafau** [comment]
@jameshp  thank you for issue. Yes `resizeToAvoidBottomInset` is set to `false` by default, but you can pass `true` as parameter and you'll get old behaviour.

**Comment by jameshp** [comment]
thanks for clarifying, I somehow missed that.

**Comment by brnyza** [comment]
I trying like this, but the keyboard is in front of the input, is it necessary other configuration?
return WebviewScaffold(
            resizeToAvoidBottomInset: true,
            url: selectedUrl,

*flutter_webview_plugin: ^0.3.11
