### ISSUE TITLE
the lib 0.3.2 is wrong with widget.resizeToAvoidBottomInset but Scaffold is  resizeToAvoidBottomPadding

### ISSUE THREAD

**Issue by woaigmz** [fluttercommunity/flutter_webview_plugin#391]
Compiler message:
file:///Users/haoran/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.2/lib/src/webview_scaffold.dart:110:7: Error: No named parameter with the name 'resizeToAvoidBottomInset'.
      resizeToAvoidBottomInset: widget.resizeToAvoidBottomPadding,
      ^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/haoran/Downloads/flutter/packages/flutter/lib/src/material/scaffold.dart:1: Context: Found this candidate, but the arguments don't match.
Compiler failed on /Users/haoran/Desktop/flutter_hyr/lib/main.dart
Error launching application on iPhone Xʀ.

**Comment by charafau** [comment]
I think this is related - (is your flutter updated?) https://github.com/fluttercommunity/flutter_webview_plugin/issues/374

**Comment by woaigmz** [comment]
> I think this is related - (is your flutter updated?) #374

thanks, I update the flutter sdk ,the problem solved
