### ISSUE TITLE
Crash on iOS 12

### ISSUE THREAD

**Issue by zhenzhg** [fluttercommunity/flutter_webview_plugin#399]
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011225c6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000111800ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011225c555 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001112865e1 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 488
	4   Foundation                          0x0000000111286a68 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   Runner                              0x000000010f9bbc79 -[FlutterWebviewPlugin closeWebView] + 361
	6   Runner                              0x000000010f9b8417 -[FlutterWebviewPlugin h<…>
Lost connection to device.
```

This is the code:

```dart
class WebViewPageState extends State<WebViewPage> {
  String _url;
  String _title;

  WebViewPageState(this._url, this._title);

  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(
          appBar: AppBar(
            title: Text(this._title),
          ),
          url: this._url,
          withLocalStorage: true,
          hidden: true,
          withZoom: false,
          withJavascript: true,
    );
  }
}
```

**Comment by charafau** [comment]
hello, thanks for report. what's flutter version and plugin version ?

**Comment by evelyne24** [comment]
I have a crash as well. See below.

**Crash**

```
08:36:14.612 1 info flutter.tools [+4277 ms] [DEVICE LOG] Timestamp                       (process)[PID]    
08:36:14.612 2 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.605855+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSwapping] 0x1336e96e0 - WebProcessCache::updateCapacity: Cache is disabled because process swap on navigation is disabled
08:36:14.860 3 info flutter.tools [ +250 ms] [DEVICE LOG] 2019-04-26 08:36:14.856788+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:Loading] 0x7fc19d122e18 - WebPageProxy::constructor: webPID = 0, pageID = 1
08:36:14.860 4 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.857315+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSwapping] 0x1336e96e0 - WebProcessCache::updateCapacity: Cache is disabled by client
08:36:14.878 5 info flutter.tools [  +17 ms] [DEVICE LOG] 2019-04-26 08:36:14.875368+0100  localhost Runner[82422]: (MobileAsset) [com.apple.mobileassetd:Notice] _MobileAssetSendCopyMatchingAssetsCommand: [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker
08:36:14.918 6 info flutter.tools [  +38 ms] [DEVICE LOG] 2019-04-26 08:36:14.912215+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSuspension] 0x7fc19d122e18 - WebPageProxy::updateThrottleState: UIProcess is taking a foreground assertion because the view is visible
08:36:14.918 7 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.912550+0100  localhost Runner[82422]: (CoreFoundation) -[NSNull length]: unrecognized selector sent to instance 0x10e07dea8
08:36:15.175 8 info flutter.tools [ +257 ms] [DEVICE LOG] 2019-04-26 08:36:15.172013+0100  localhost Runner[82422]: (CoreFoundation) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x10e07dea8'
08:36:15.175 9 info flutter.tools [        ] [DEVICE LOG] *** First throw call stack:
08:36:15.182 10 info flutter.tools [   +3 ms] [DEVICE LOG] (
08:36:15.182 11 info flutter.tools [        ] [DEVICE LOG] 	0   CoreFoundation                      0x000000010de106fb __exceptionPreprocess + 331
08:36:15.182 12 info flutter.tools [        ] [DEVICE LOG] 	1   libobjc.A.dylib                     0x000000010d3b4ac5 objc_exception_throw + 48
08:36:15.182 13 info flutter.tools [        ] [DEVICE LOG] 	2   CoreFoundation                      0x000000010de2eab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
08:36:15.182 14 info flutter.tools [        ] [DEVICE LOG] 	3   CoreFoundation                      0x000000010de15443 ___forwarding___ + 1443
08:36:15.182 15 info flutter.tools [        ] [DEVICE LOG] 	4   CoreFoundation                      0x000000010de17238 _CF_forwarding_prep_0 + 120
08:36:15.182 16 info flutter.tools [        ] [DEVICE LOG] 	5   CoreFoundation                      0x000000010ddca1fb _CFURLCreateWithURLString + 75
08:36:15.182 17 info flutter.tools [        ] [DEVICE LOG] 	6   Foundation                          0x000000010c8f9b20 -[NSURL(NSURL) initWithString:relativeToURL:] + 309
08:36:15.182 18 info flutter.tools [        ] [DEVICE LOG] 	7   Foundation                          0x000000010c8fa3c0 +[NSURL(NSURL) URLWithString:relativeToURL:] + 59
08:36:15.182 19 info flutter.tools [        ] [DEVICE LOG] 	8   Runner                              0x00000001086547<…>
08:36:15.194 20 info flutter.tools [  +14 ms] *** First throw call stack:
08:36:15.194 21 info flutter.tools [        ] (
08:36:15.194 22 info flutter.tools [        ] 	0   CoreFoundation                      0x000000010de106fb __exceptionPreprocess + 331
08:36:15.194 23 info flutter.tools [        ] 	1   libobjc.A.dylib                     0x000000010d3b4ac5 objc_exception_throw + 48
08:36:15.194 24 info flutter.tools [        ] 	2   CoreFoundation                      0x000000010de2eab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
08:36:15.194 25 info flutter.tools [        ] 	3   CoreFoundation                      0x000000010de15443 ___forwarding___ + 1443
08:36:15.194 26 info flutter.tools [        ] 	4   CoreFoundation                      0x000000010de17238 _CF_forwarding_prep_0 + 120
08:36:15.194 27 info flutter.tools [        ] 	5   CoreFoundation                      0x000000010ddca1fb _CFURLCreateWithURLString + 75
08:36:15.194 28 info flutter.tools [        ] 	6   Foundation                          0x000000010c8f9b20 -[NSURL(NSURL) initWithString:relativeToURL:] + 309
08:36:15.194 29 info flutter.tools [        ] 	7   Foundation                          0x000000010c8fa3c0 +[NSURL(NSURL) URLWithString:relativeToURL:] + 59
08:36:15.194 30 info flutter.tools [        ] 	8   Runner                              0x00000001086547<…>
```

**Environment**

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/evelina/bin/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/evelina/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/evelina/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/evelina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPhone Xʀ • CA85005F-1E7B-4C9F-8DA5-0AF5BE0B6699 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by evelyne24** [comment]
> I have a crash as well. See below.
> 
> **Crash**
> 
> ```
> 08:36:14.612 1 info flutter.tools [+4277 ms] [DEVICE LOG] Timestamp                       (process)[PID]    
> 08:36:14.612 2 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.605855+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSwapping] 0x1336e96e0 - WebProcessCache::updateCapacity: Cache is disabled because process swap on navigation is disabled
> 08:36:14.860 3 info flutter.tools [ +250 ms] [DEVICE LOG] 2019-04-26 08:36:14.856788+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:Loading] 0x7fc19d122e18 - WebPageProxy::constructor: webPID = 0, pageID = 1
> 08:36:14.860 4 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.857315+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSwapping] 0x1336e96e0 - WebProcessCache::updateCapacity: Cache is disabled by client
> 08:36:14.878 5 info flutter.tools [  +17 ms] [DEVICE LOG] 2019-04-26 08:36:14.875368+0100  localhost Runner[82422]: (MobileAsset) [com.apple.mobileassetd:Notice] _MobileAssetSendCopyMatchingAssetsCommand: [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker
> 08:36:14.918 6 info flutter.tools [  +38 ms] [DEVICE LOG] 2019-04-26 08:36:14.912215+0100  localhost Runner[82422]: (WebKit) [com.apple.WebKit:ProcessSuspension] 0x7fc19d122e18 - WebPageProxy::updateThrottleState: UIProcess is taking a foreground assertion because the view is visible
> 08:36:14.918 7 info flutter.tools [        ] [DEVICE LOG] 2019-04-26 08:36:14.912550+0100  localhost Runner[82422]: (CoreFoundation) -[NSNull length]: unrecognized selector sent to instance 0x10e07dea8
> 08:36:15.175 8 info flutter.tools [ +257 ms] [DEVICE LOG] 2019-04-26 08:36:15.172013+0100  localhost Runner[82422]: (CoreFoundation) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x10e07dea8'
> 08:36:15.175 9 info flutter.tools [        ] [DEVICE LOG] *** First throw call stack:
> 08:36:15.182 10 info flutter.tools [   +3 ms] [DEVICE LOG] (
> 08:36:15.182 11 info flutter.tools [        ] [DEVICE LOG] 	0   CoreFoundation                      0x000000010de106fb __exceptionPreprocess + 331
> 08:36:15.182 12 info flutter.tools [        ] [DEVICE LOG] 	1   libobjc.A.dylib                     0x000000010d3b4ac5 objc_exception_throw + 48
> 08:36:15.182 13 info flutter.tools [        ] [DEVICE LOG] 	2   CoreFoundation                      0x000000010de2eab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 08:36:15.182 14 info flutter.tools [        ] [DEVICE LOG] 	3   CoreFoundation                      0x000000010de15443 ___forwarding___ + 1443
> 08:36:15.182 15 info flutter.tools [        ] [DEVICE LOG] 	4   CoreFoundation                      0x000000010de17238 _CF_forwarding_prep_0 + 120
> 08:36:15.182 16 info flutter.tools [        ] [DEVICE LOG] 	5   CoreFoundation                      0x000000010ddca1fb _CFURLCreateWithURLString + 75
> 08:36:15.182 17 info flutter.tools [        ] [DEVICE LOG] 	6   Foundation                          0x000000010c8f9b20 -[NSURL(NSURL) initWithString:relativeToURL:] + 309
> 08:36:15.182 18 info flutter.tools [        ] [DEVICE LOG] 	7   Foundation                          0x000000010c8fa3c0 +[NSURL(NSURL) URLWithString:relativeToURL:] + 59
> 08:36:15.182 19 info flutter.tools [        ] [DEVICE LOG] 	8   Runner                              0x00000001086547<…>
> 08:36:15.194 20 info flutter.tools [  +14 ms] *** First throw call stack:
> 08:36:15.194 21 info flutter.tools [        ] (
> 08:36:15.194 22 info flutter.tools [        ] 	0   CoreFoundation                      0x000000010de106fb __exceptionPreprocess + 331
> 08:36:15.194 23 info flutter.tools [        ] 	1   libobjc.A.dylib                     0x000000010d3b4ac5 objc_exception_throw + 48
> 08:36:15.194 24 info flutter.tools [        ] 	2   CoreFoundation                      0x000000010de2eab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 08:36:15.194 25 info flutter.tools [        ] 	3   CoreFoundation                      0x000000010de15443 ___forwarding___ + 1443
> 08:36:15.194 26 info flutter.tools [        ] 	4   CoreFoundation                      0x000000010de17238 _CF_forwarding_prep_0 + 120
> 08:36:15.194 27 info flutter.tools [        ] 	5   CoreFoundation                      0x000000010ddca1fb _CFURLCreateWithURLString + 75
> 08:36:15.194 28 info flutter.tools [        ] 	6   Foundation                          0x000000010c8f9b20 -[NSURL(NSURL) initWithString:relativeToURL:] + 309
> 08:36:15.194 29 info flutter.tools [        ] 	7   Foundation                          0x000000010c8fa3c0 +[NSURL(NSURL) URLWithString:relativeToURL:] + 59
> 08:36:15.194 30 info flutter.tools [        ] 	8   Runner                              0x00000001086547<…>
> ```
> **Environment**
> 
> ```
> [✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
>     • Flutter version 1.2.1 at /Users/evelina/bin/flutter
>     • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/evelina/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/evelina/Library/Android/sdk
>     • ANDROID_SDK_ROOT = /Users/evelina/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • ios-deploy 2.0.0
>     • CocoaPods version 1.6.0.beta.1
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 34.0.2
>     • Dart plugin version 183.5901
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.1.1)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 34.0.4
>     • Dart plugin version 191.7019
> 
> [✓] VS Code (version 1.33.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.25.1
> 
> [✓] Connected device (1 available)
>     • iPhone Xʀ • CA85005F-1E7B-4C9F-8DA5-0AF5BE0B6699 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> 
> • No issues found!
> ```

Also crashes on iPhone XS 12.2

**Comment by radvansky-tomas** [comment]
Same here

**Comment by boozy-ph** [comment]
Same issue using `flutter_webview_plugin: ^0.3.9+1` on real device iPhone iOS 13.1.2

```
[+91102 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/878EF4F9-313A-4F9F-A23E-111C67810598/tmp/bzy_mobile_app3XJJX8/bzy_mobile_app/)
[        ] Sending to VM service: _deleteDevFS({fsName: bzy_mobile_app})
[ +258 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 258,306ms.
```

Flutter doctor
```
[✓] Flutter (Channel dev, v1.12.16, on Mac OS X 10.15.1 19B88, locale en-PH)
    • Flutter version 1.12.16 at /Users/boozylifeinc/Workspace/flutter
    • Framework revision 37f9c54116 (7 days ago), 2019-11-27 11:33:38 -0800
    • Engine revision fad1b23c42
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/boozylifeinc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone • 1c53ded8f584404adc2e2202d47981500698eedc • ios • iOS 13.1.2

• No issues found!
```

**Comment by boozy-ph** [comment]
Hi guys, I managed to fix my issue by encoding URL with this `Uri.encodeFull(my_URL);`.

**Comment by charafau** [comment]
I believe that issue is fixed now, closing for now, open new one if re-occures

**Comment by DavidMGT** [comment]
me too 
on    version: "0.3.10+2"
crashed!!!!
