### ISSUE TITLE
H5 video cannot be played in Fullscreen，the fullscreen button is unclickable

### ISSUE THREAD

**Issue by lycstar** [fluttercommunity/flutter_webview_plugin#405]
HTML video cannot be played in full screen,the full screen button is not clickable.

**Comment by lyzcw** [comment]
Me too. It's a bad experience that the mobile  can't play video in full screen.

**Comment by charafau** [comment]
Thank you for issue. It's a duplicate of https://github.com/fluttercommunity/flutter_webview_plugin/issues/423
