### ISSUE TITLE
Conflict in file provider path

### ISSUE THREAD

**Issue by AlexVincent525** [fluttercommunity/flutter_webview_plugin#411]
Hi there!
Today I just met a problem with file provider path, which this package's is conflict with [multi_image_picker](https://github.com/Sh1d0w/multi_image_picker), and the author is here [@Sh1d0w](https://github.com/Sh1d0w).

Here's log for the error:
```
Error:
    Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from [:flutter_webview_plugin] AndroidManifest.xml:17:17-50
    is also present at [com.sangcomz:FishBun:0.9.0] AndroidManifest.xml:19:17-55 value=(@xml/provider_paths).
    Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
```
FishBun is provided by multi image picker, so I think maybe this is related.
I'm using webview_plugin with 0.3.5, and multi_image_picker with 4.2.1.

Hope this can be figured out and fixed ASAP!

**Comment by AlexVincent525** [comment]
As FishBun updated with custom provider fixes, can webview plugin uses the same method to avoid this happened? @charafau 
See PR here: https://github.com/sangcomz/FishBun/pull/151

**Comment by merRen22** [comment]
@AlexVincent525  updating multi_image_picker to latest version fixed everything for me it updated the FishBun version

**Comment by AlexVincent525** [comment]
@merRen22 Yep. But if this won't fix with custom provider or some other methods, it will happen again if there's a conflict like this one.

**Comment by xiaobeiy** [comment]
flutter 1.9.1+hotfix6

install_plugin: 2.0.1
The err log is:
```
Attribute provider#androidx.core.content.FileProvider@authorities value=(cn.net.shihong.rcb.fileProvider.install) from [:install_plugin] AndroidManifest.xml:12:13-72
        is also present at [:flutter_webview_plugin] AndroidManifest.xml:11:13-64 value=(cn.net.shihong.rcb.fileprovider).
        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:10:9-18:20 to override.
```

**Comment by cucumbersunny** [comment]
That's because the install_plugin uese exactly the same provide name.
try add
`<provider
            android:name="androidx.core.content.FileProvider"
            tools:replace="android:authorities"
            android:authorities="${applicationId}.fileProvider.install"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                tools:replace="android:resource"
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_install_paths"/>
        </provider>`
to the file 'AndroidManifest.xml' bellow application tag

**Comment by The-five-stooges** [comment]
#621 this solution solve the problem, also add xmlns:tools="http://schemas.android.com/tools" in the manifest tag

**Comment by The-five-stooges** [comment]
Duplicate of #621

**Comment by AlexVincent525** [comment]
It's already done with https://github.com/sangcomz/FishBun/pull/151 . So I'm going to close the issue.


> #621 this solution solve the problem, also add xmlns:tools="http://schemas.android.com/tools" in the manifest tag

This one works too.
