### ISSUE TITLE
How to hidden a div

### ISSUE THREAD

**Issue by codlin** [fluttercommunity/flutter_webview_plugin#416]
I want to load a url, then modify the div element of the html, e.g.: 
from 
`<div class="goods-bottom-bar"></div>`
to 
`<div class="goods-bottom-bar" style="display:none;"></div>`
then display in flutter widget.
Does the plugin have API to achieve this? 

Thanks.

**Comment by muffinjello** [comment]
Use the evalJavascript function to do this. For example, if the page in WebView has jQuery already running, this would work:
`flutterWebViewPlugin.evalJavascript("$('goods-bottom-bar').css('display', 'none');");`

**Comment by charafau** [comment]
thanks @muffinjello for help. that's the correct answer. closing

**Comment by codlin** [comment]
@muffinjello Thanks a lot.

**Comment by Jazzykhan** [comment]
where to paste this line i want to hide menu from my webview?
thanks
