### ISSUE TITLE
Pageview and webview

### ISSUE THREAD

**Issue by wickedman1976** [fluttercommunity/flutter_webview_plugin#420]
Is there any possibility that this can work with a pageview (carousel). 

The official webview seems to leak between swipes. 

Thanks

Nathan

**Comment by premy** [comment]
I use it with BottomNavBar no problem, so it should be able to work with pageview also. Use a normal Scaffold, then set the body as follows:
`body: WebviewScaffold(url:urlString)`

Then create a method for handling Tab Tapped event:
```void onTabTapped(int index) {
 
   setState(() {
     currentPage = index;
   switch (index) {
      case 0:
      print("case 0:");
      urlString = "http://www.exclusivoenem.com.br/vslides.aspx";
       break;
      case 1:
      urlString ="http://www.exclusivoenem.com.br/inv.aspx?m=true&aid=$aid";
       break;
      case 2:
      urlString = "http://www.exclusivoenem.com.br/cal.aspx";
        break;
         case 3:
      urlString="http://www.exclusivoenem.com.br/vdo.aspx";
       break;
       
    }
    webView.reloadUrl(urlString);
  
   });
 }  ```

And of course you need to initialize it:

```class _HomeScreenState extends State<HomeScreen> {
  final webView = FlutterWebviewPlugin();
  int currentPage = 0;
var urlString = "";```

**Comment by charafau** [comment]
hi, if you're asking if you can embed webview withing carousel - then answer is no, unfortunately. it opens new screen / activity and then loads it's content.
