### ISSUE TITLE
In order to cultivate flutter ecosystem, we hope to implement JsBridge interface as soon as possible.

### ISSUE THREAD

**Issue by lyzcw** [fluttercommunity/flutter_webview_plugin#424]
As the title.

**Comment by muffinjello** [comment]
Who is "we" (aside from yourself)? By flutter ecosystem did you mean flutter WebView plugin ecosystem? Is this a request for someone else to implement this for you?

**Comment by lyzcw** [comment]
@muffinjello It should be the flutter ecosystem. Because of the widespread popularity of h5, the flutter ecosystem has to coexist with H5 for a long time. The integrity of flutter_webview_plugin can not be separated from JSBridge. We hope that the flutter community will contribute to the perfect experience for everyone. Thank you again for all contributions.

**Comment by muffinjello** [comment]
I just took a look and saw that you have a JSBridge repository - it looks very elegant but I'm afraid I don't entirely understand how it works. Is the JavaScript messaging a Java server or port of sorts? 

It would be conceivable that a helper class which makes a local HTTP server which is then pinged with ajax requests to transfer data into the system. I'm doubtful if this is worth it in comparison to listening for onUrlChanged.

**Comment by lyzcw** [comment]
JSBridge, my understanding is that h5's JS calls flutter through WebView's JS bridge. It is mainly used for JS calls to devices, such as using JS to set up cameras, microphones and so on. It can also call up custom flutter functions.

**Comment by charafau** [comment]
As long as it sounds interesting, I think it's way out of scope of this project (which is initially only to have some sort of webview - mainly for authentication, opening simple pages until Google's official webview is done). 

Nothing stops you from using this project as base for your bridge though, but as for whole implementation we lack manpower. 

Closing for now.
