### ISSUE TITLE
How do I do webSettings in flutter?

### ISSUE THREAD

**Issue by jockebq** [fluttercommunity/flutter_webview_plugin#427]
On my Android Studio project (non flutter based) I can do this:
```
        webSettings.setMediaPlaybackRequiresUserGesture(false);
```
This will allow autoplay of media without user input.

How do I this in flutter_webview_plugin?

Thank you!

**Comment by charafau** [comment]
hi @jockebq  it's not possible to add this currently. if you want to set this option, we need to add this to plugin's api (like the rest values). PRs welcome (but create an issue first)

**Comment by jockebq** [comment]
Thank you for the reply, I created a new issue as you suggested:
`https://github.com/fluttercommunity/flutter_webview_plugin/issues/430`

**Comment by umi0410** [comment]
Is there any progress? I aslo want to play videoes automatically without user interaction.
It works on mobile chrome but doesn't work on flutter webview.

**Comment by bubinyang** [comment]
> 有没有任何进展？我也想在没有用户交互的情况下自动播放视频。 它适用于移动 chrome，但不适用于 flutter webview。

did you solve it?
