### ISSUE TITLE
access mobile camera

### ISSUE THREAD

**Issue by Seven7up** [fluttercommunity/flutter_webview_plugin#440]
hi

I have a web page to show the camera in mobile chrome and firefox I can access to the camera but in flutter web view I can access the  camera

**Comment by scofield-hello** [comment]
this plugin did't ask for permissions when use camera

**Comment by Seven7up** [comment]
> this plugin did't ask for permissions when use camera


Hi, I raised my question in the stack but no one did  answer

https://stackoverflow.com/questions/56478375/access-the-camera-on-flutter-webview

**Comment by Seven7up** [comment]
> this plugin did't ask for permissions when use camera

what I can do then?

**Comment by scofield-hello** [comment]
@Seven7up you should ask for the camera permission before open camera in WebView.

**Comment by charafau** [comment]
When I think about it, that's what we should probably do and try not to make this plugin too big. Closing for now.

**Comment by scofield-hello** [comment]
@charafau What you said is very reasonable, it will be more better if you point it out at README file.

**Comment by OPY-bbt** [comment]
> When I think about it, that's what we should probably do and try not to make this plugin too big. Closing for now.

but why the demo in this project dont need permission?

**Comment by rahul69x** [comment]
Same issue is here. I am making an app for live classes. But the flutter webview is not asking about  camera and mic permission.
