### ISSUE TITLE
Android keyboard covering the webview

### ISSUE THREAD

**Issue by sooxiaotong** [fluttercommunity/flutter_webview_plugin#454]
## System info

Issue occurs on: Android
Plugin version: latest
Flutter doctor output: no related

## Steps to Reproduce
something like this in Android, i cant even scroll the content (I don't have android phone now, i just replicate in iOS :P
![IMG_4061](https://user-images.githubusercontent.com/13378059/59553891-585c7500-8fce-11e9-8c82-24506f223391.PNG)

it works in iOS while it pushes the content up after the keyboard show up, and it can scroll too
![IMG_4062](https://user-images.githubusercontent.com/13378059/59553900-6dd19f00-8fce-11e9-9017-01e89bb0e54d.PNG)

**Comment by mimokrok** [comment]
Yep. I have the same issue.

**Comment by vanosidor** [comment]
And I have the same problem too

**Comment by jameshp** [comment]
Maybe you have the same problem I had? https://github.com/fluttercommunity/flutter_webview_plugin/issues/379

**Comment by charafau** [comment]
Possible duplicate, closing for now, will re-open when needed https://github.com/fluttercommunity/flutter_webview_plugin/issues/379
