### ISSUE TITLE
How to access camera?

### ISSUE THREAD

**Issue by aagarwal1012** [fluttercommunity/flutter_webview_plugin#460]
It would be really helpful if someone can tell how to access the camera from the webview.

**Comment by hanjianchun** [comment]
open camera access first,like this:

Map<PermissionGroup, PermissionStatus> permissions =
    await PermissionHandler().requestPermissions([PermissionGroup.storage,PermissionGroup.camera]);

**Comment by charafau** [comment]
Like above - you need to request permissions first.
