### ISSUE TITLE
stopLoading nog working on iOS

### ISSUE THREAD

**Issue by jeroensmeets** [fluttercommunity/flutter_webview_plugin#468]
## System info

Issue occurs on: iOS
Plugin version: 0.3.5
Flutter doctor output:

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F203, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)
```

## Steps to Reproduce

```
final wv = new FlutterWebviewPlugin();

// from initState()
_onStateChanged = wv.onStateChanged.listen((WebViewStateChanged state) async {

      // do not follow links to pdf documents
      if (state.type == WebViewState.shouldStart) {
        if (state.url.toLowerCase().endsWith('.pdf')) {
          print('stop loading');
          wv.stopLoading();
          launchURL(state.url);
        }
      }

});
```

```
void launchURL(url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
```

The string `stop loading` is printed, and the pdf opens in an external viewer. When I close the viewer, the pdf is also in the webview. It also happens with a link to a webpage, after returning from the browser.

No log lines on iOS that are relevant for this issue.

## output of running `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F203, locale nl-NL)
    • Flutter version 1.7.8+hotfix.2 at /Users/jeroensmeets/env-bin/flutter
    • Framework revision 2e540931f7 (3 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeroensmeets/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jeroensmeets/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone • c4241b57871c0ffcd7bb78de8f8bff94aceb6d72 • ios • iOS 12.3.1

• No issues found!
```

**Comment by jeroensmeets** [comment]
After further investigation, I found the event fired twice for one click on iOS.

**Comment by xalikoutis** [comment]
Hi @jeroensmeets same problem here. What's your solution?

**Comment by jeroensmeets** [comment]
Hi @xalikoutis the state changed handler is called for different state types, I now check on this:

```
_onStateChanged = wv.onStateChanged.listen((WebViewStateChanged state) async {

  var isPdf = state.url.toLowerCase().indexOf('.pdf') > -1;
  var isExternalLink = !state.url.startsWith(baseUrl);

  if (isPdf || isExternalLink) {
    wv.stopLoading();
    if (state.type == WebViewState.shouldStart) {
      launchURL(state.url);
    }
  }
});
```

**Comment by xalikoutis** [comment]
Yeah i have exactly the same implementation that works in Android cause stopLoading also stops the navigation but on IOS doesnt cause that's how it is implemented inside wkwebview.

So the above code on IOS will continue navigation to the url and also launch it externally id it pdf or external.

**Comment by rivetingpeppermint** [comment]
@charafau 

> After further investigation, I found the event fired twice for one click on iOS.

This is still happening as of now. My code is very similar to @jeroensmeets' except my links are just links to other websites. It does launch the browser, but it still launches twice. I used the iPhone X (iOS 13) simulator with Flutter 1.17.5. Any tips on what to do? The behavior doesn't happen with Android devices.

**Comment by rivetingpeppermint** [comment]
I tried @jeroensmeets' code above to open links on a browser and it works fine: 

```
flutterWebviewPlugin.onStateChanged.listen((WebViewStateChanged state) async {
      if (state.url != htmlString) {
      flutterWebviewPlugin.stopLoading();
      if (state.type == WebViewState.shouldStart) {
        launchURL(state.url);
      }
    }
  });
```

My Webview URL isn't actually a URL, but HTML content passed as a URL using 
```
Uri.dataFromString(htmlString, mimeType: 'text/html', encoding: utf8).toString();
``` 
The problem is if there's an embedded YouTube video iframe inside my HTML, the webview will open the device's browser without any actions or clicks. Only happens on iOS, and only happens with embedded YT videos. Ordinary links behave normally. Any ideas on how to deal with this? @charafau

**Comment by charafau** [comment]
Hello! 
Please notice that plugin is mostly in read only state and I encourage everyone to use official one of they can. That said, plugin was created as simple web view but you seem to need more complete expensive with multimedia videos. There was one fix for your problem in past but it introduced more problems than it solved.
If you need many features from web view I'd consider implanting this natively
