### ISSUE TITLE
How can I remove or disable the "scroll back to top" button?

### ISSUE THREAD

**Issue by joelbrostrom** [fluttercommunity/flutter_webview_plugin#474]
Hi, I'm using this package in production and our client want to get rid of the button that appears when scrolling down a web page. 
It's a big square with a circle containing an up arrow and does not fit the app theme.

I thought it would be simple, but with no documentation and limited time I cant find any toggle feature that accomplish this.

Have I just missed something?

**Comment by shinriyo** [comment]
```
  Future<bool> _onWillPop() async {
    return false;
  }
```

```
    return WillPopScope(
      onWillPop: _onWillPop,
```
