### ISSUE TITLE
Web功能请教

### ISSUE THREAD

**Issue by Yxjie** [fluttercommunity/flutter_webview_plugin#477]
怎么拿到加载web界面的title，还有此插件是否有canGoBack方法，不像Demo那样 Appbar的返回按钮只适合返回上一个Flutter界面。底部goback按钮，back到首页后 在点击就没反应了

**Comment by hanjianchun** [comment]
可以监听url改变，使用evalJavascript 获取title：
flutterWebViewPlugin.onUrlChanged.listen((url){
      flutterWebViewPlugin.evalJavascript("window.document.title").then((result){
        title = result;
      });
    });

此插件我没找到canGoBack方法，我监听url的change事件，如果当前按下返回并且url和我初始打开时的链接一样，就让它关闭，否则调用 flutterWebViewPlugin.goBack();
