### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by buster95** [fluttercommunity/flutter_webview_plugin#478]
I want to use this web view inside Positioned into a Stack Widget but webview is always over the others widgets

## System info

Issue occurs on: iOS / Android / both
Plugin version: 0.3.5
Flutter doctor output:

```
paste it here...
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by firstlevelIT** [comment]
Did you solved the issue? How? Thanks

**Comment by firstlevelIT** [comment]
very communicative
