### ISSUE TITLE
WebviewScaffold does not send headers when flutterWebViewPlugin.reloadUrl(myUrl) is called.

### ISSUE THREAD

**Issue by joelbrostrom** [fluttercommunity/flutter_webview_plugin#481]
When reloading a web page in an WebviewScaffold the headers are not passed with the new url.

When creating a WebviewScaffold the initial page will include the specified header.
```
return WebviewScaffold(
            resizeToAvoidBottomInset: true,
            withJavascript: true,
            url: initialUrl,
            withZoom: false,
            withLocalStorage: true,
            hidden: false,
            headers: {
              'X-Device-OS': '${Platform.operatingSystem}',
              'X-App-Version': '${packageInfo.version}'
            },
          );
```

But when reloading the WebviewScaffold with a new (or the same) url the request will not include the headers specified when creating the WebviewScaffold.
```
 flutterWebViewPlugin.reloadUrl(url);
```

How can i make the headers persist throughout the life of the WebviewScaffold?

**Comment by charafau** [comment]
added headers as optional in 0.3.7
