### ISSUE TITLE
Can't get camera access (Web Angular - getUserMedia)

### ISSUE THREAD

**Issue by JeronimoRepetto** [fluttercommunity/flutter_webview_plugin#484]
I cant open the device camera, please help! 

**Steps to Reproduce**

Create a webView like:
And call it.
> import 'package:flutter/material.dart';
> import 'package:permission_handler/permission_handler.dart';
> 
> class WebViewPage extends StatefulWidget {
>   _WebViewPageState createState() => _WebViewPageState();
> }
> 
> class _WebViewPageState extends State<WebViewPage> {
>   PermissionStatus _permissionStatus = PermissionStatus.unknown;
> 
>   @override
>   void initState() {
>     _listenForPermissionStatus();
>     super.initState();
>   }
> 
>   Future<void> requestPermission(PermissionGroup permission) async {
>     final List<PermissionGroup> permissions = <PermissionGroup>[permission];
>     final Map<PermissionGroup, PermissionStatus> permissionRequestResult =
>     await PermissionHandler().requestPermissions(permissions);
>     setState(() {
>       print(permissionRequestResult);
>       _permissionStatus = permissionRequestResult[permission];
>       print(_permissionStatus);
>     });
>   }
> 
>   void _listenForPermissionStatus() {
>     final Future<PermissionStatus> statusFuture =
>     PermissionHandler().checkPermissionStatus(PermissionGroup.camera);
> 
>     statusFuture.then((PermissionStatus status) {
>       if(status == PermissionStatus.denied || status == PermissionStatus.disabled)
>         requestPermission(PermissionGroup.camera).then((_){
>           requestPermission(PermissionGroup.storage);
>         });
>     });
>   }  
> 
> @override
>   Widget build(BuildContext context) {
>       return new MaterialApp(
>         title: 'Example',
>         color: Ui.primaryColor,
>         theme: new ThemeData(
>           primaryColor: Colors.blue,
>         ),
>         routes: {
>           "/": (_) => new WebviewScaffold(
>                 withJavascript: true,
>                 appCacheEnabled: true,
>                 allowFileURLs: true,
>                 primary: true,
>                 geolocationEnabled: true,
>                 withLocalStorage: true,
>                 supportMultipleWindows: true,
>                 url: "https://webrtc.github.io/samples/src/content/getusermedia/gum/",
>                 appBar: new AppBar(
>                   title: Text("Example")
>                 ),
>               ),
>         },
>       );
>   }
> 

 **Logs**

[+1443 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemSound.play' message.
[   +1 ms] V/AudioManager(21175): playSoundEffect   effectType: 0
[        ] V/AudioManager(21175): querySoundEffectsEnabled...
[  +17 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter.baseflow.com/permissions/methods'
[   +2 ms] V/DartMessenger(21175): Deferring to registered handler to process message.
[ +156 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setApplicationSwitcherDescription' message.
[   +1 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter_webview_plugin'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[  +30 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter.baseflow.com/permissions/methods'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[  +69 ms] V/LifecycleChannel(21175): Sending AppLifecycleState.inactive message.
[  +15 ms] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[        ] D/ZrHung.AppEyeUiProbe(21175): stop checker.
[  +37 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter_webview_plugin'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[  +78 ms] I/WebViewFactory(21175): Loading com.android.chrome version 75.0.3770.101 (code 377010137)
[ +236 ms] I/cr_LibraryLoader(21175): Time to load native libraries: 7 ms (timestamps 4990-4997)
[  +73 ms] I/chromium(21175): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
[   +1 ms] D/ZrHung.AppEyeUiProbe(21175): Current Activity:false
[        ] D/ZrHung.AppEyeUiProbe(21175): not watching, wait.
[        ] I/cr_LibraryLoader(21175): Expected native library version number "75.0.3770.101", actual native library version number "75.0.3770.101"
[  +42 ms] W/cr_ChildProcLH(21175): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
[   +6 ms] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
[  +25 ms] I/cr_BrowserStartup(21175): Initializing chromium process, singleProcess=false
[  +83 ms] E/chromium(21175): [ERROR:filesystem_posix.cc(89)] stat /data/user/0/app.miiii.mibarrioapp/cache/WebView/Crashpad: No such file or directory (2)
[        ] E/chromium(21175): [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/app.miiii.mibarrioapp/cache/WebView/Crashpad: No such file or directory (2)
[ +182 ms] D/ConnectivityManager(21175): requestNetwork and the calling app is: app.miiii.mibarrioapp
[  +28 ms] W/iii.mibarrioap(21175): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
[   +2 ms] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist,
reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light
greylist, reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelec
tionEventTracker$SelectionEvent; (light greylist, reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionE
ventTracker$SelectionEvent; (light greylist, reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist,
reflection)
[        ] W/iii.mibarrioap(21175): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelect
ionEventTracker$SelectionEvent; (light greylist, reflection)
[  +62 ms] V/AudioManager(21175): isWiredHeadsetOn...
[   +3 ms] W/cr_media(21175): Requires BLUETOOTH permission
[   +5 ms] I/iGraphics(21175): [0030080c] opt app: 0
[  +24 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setSystemUIOverlayStyle' message.
[   +4 ms] D/ConnectivityManager(21175): requestNetwork and the calling app is: app.miiii.mibarrioapp
[  +55 ms] I/ViewRootImpl(21175): jank_removeInvalidNode all the node in jank list is out of time
[   +1 ms] V/TextInputChannel(21175): Sending message to update editing state: 
[        ] V/TextInputChannel(21175): Text: 00593384901
[        ] V/TextInputChannel(21175): Selection start: 11
[        ] V/TextInputChannel(21175): Selection end: 11
[        ] V/TextInputChannel(21175): Composing start: -1
[        ] V/TextInputChannel(21175): Composing end: -1
[        ] V/DartMessenger(21175): Sending message with callback over channel 'flutter/textinput'
[  +61 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setApplicationSwitcherDescription' message.
[        ] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setApplicationSwitcherDescription' message.
[   +1 ms] W/VideoCapabilities(21175): Unrecognized profile 4 for video/hevc
[   +1 ms] W/VideoCapabilities(21175): Unrecognized profile/level 0/0 for video/mpeg2
[        ] W/VideoCapabilities(21175): Unrecognized profile/level 0/2 for video/mpeg2
[        ] W/VideoCapabilities(21175): Unrecognized profile/level 0/3 for video/mpeg2
[        ] I/VideoCapabilities(21175): Unsupported profile 5 for video/mpeg2
[   +5 ms] I/chatty  (21175): uid=10378(app.miiii.mibarrioapp) Chrome_InProcGp identical 2 lines
[        ] I/VideoCapabilities(21175): Unsupported profile 5 for video/mpeg2
[        ] W/VideoCapabilities(21175): Unrecognized profile/level 1/32 for video/mp4v-es
[        ] W/VideoCapabilities(21175): Unrecognized profile/level 32768/2 for video/mp4v-es
[        ] W/VideoCapabilities(21175): Unrecognized profile/level 32768/64 for video/mp4v-es
[  +18 ms] I/VideoCapabilities(21175): Unsupported profile 4 for video/mp4v-es
[  +14 ms] W/cr_MediaCodecUtil(21175): HW encoder for video/avc is not available on this device.
[  +29 ms] D/NetworkSecurityConfig(21175): No Network Security Config specified, using platform default
[ +208 ms] V/DartMessenger(21175): Sending message with callback over channel 'flutter_webview_plugin'
[ +536 ms] D/HwGalleryCacheManagerImpl(21175): mIsEffect:false
[ +137 ms] W/InputMethodManager(21175): startInputReason = 1
[  +70 ms] D/ZrHung.AppEyeUiProbe(21175): notify runnable to start.
[        ] D/ZrHung.AppEyeUiProbe(21175): restart watching
[        ] V/LifecycleChannel(21175): Sending AppLifecycleState.resumed message.
[   +5 ms] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[        ] I/flutter (21175): {PermissionGroup.camera: PermissionStatus.granted}
[        ] I/flutter (21175): PermissionStatus.granted
[  +95 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter.baseflow.com/permissions/methods'
[   +4 ms] V/DartMessenger(21175): Deferring to registered handler to process message.
[  +32 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setApplicationSwitcherDescription' message.
[  +13 ms] V/LifecycleChannel(21175): Sending AppLifecycleState.inactive message.
[        ] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[        ] D/ZrHung.AppEyeUiProbe(21175): stop checker.
[ +511 ms] V/DartMessenger(21175): Sending message with callback over channel 'flutter_webview_plugin'
[ +334 ms] D/ZrHung.AppEyeUiProbe(21175): Current Activity:false
[        ] D/ZrHung.AppEyeUiProbe(21175): not watching, wait.
[ +308 ms] I/flutter (21175): {PermissionGroup.storage: PermissionStatus.granted}
[        ] I/flutter (21175): PermissionStatus.granted
[        ] D/ZrHung.AppEyeUiProbe(21175): notify runnable to start.
[        ] D/ZrHung.AppEyeUiProbe(21175): restart watching
[  +14 ms] V/LifecycleChannel(21175): Sending AppLifecycleState.resumed message.
[        ] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[   +1 ms] W/InputMethodManager(21175): startInputReason = 1
[   +2 ms] V/DartMessenger(21175): Received message from Dart over channel 'flutter/platform'
[        ] V/DartMessenger(21175): Deferring to registered handler to process message.
[        ] V/PlatformChannel(21175): Received 'SystemChrome.setApplicationSwitcherDescription' message.
[+1631 ms] W/InputMethodManager(21175): startInputReason = 4
[  +36 ms] I/HwSecImmHelper(21175): mSecurityInputMethodService is null
[  +41 ms] I/CameraManagerGlobal(21175): Connecting to camera service
[ +140 ms] I/chromium(21175): [INFO:CONSOLE(41)] "[object DOMException]", source: https://webrtc.github.io/samples/src/content/getusermedia/gum/js/main.js (41)
[+8508 ms] E/        (21175): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[ +407 ms] I/HwSecImmHelper(21175): mSecurityInputMethodService is null
[  +56 ms] I/chromium(21175): [INFO:CONSOLE(41)] "[object DOMException]", source: https://webrtc.github.io/samples/src/content/getusermedia/gum/js/main.js (41)
[+32127 ms] W/InputMethodManager(21175): startInputReason = 8
[  +17 ms] W/IInputConnectionWrapper(21175): getExtractedText on inactive InputConnection
[   +4 ms] W/IInputConnectionWrapper(21175): getTextBeforeCursor on inactive InputConnection
[ +223 ms] V/LifecycleChannel(21175): Sending AppLifecycleState.inactive message.
[        ] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[        ] D/ZrHung.AppEyeUiProbe(21175): stop checker.
[ +126 ms] W/libEGL  (21175): EGLNativeWindowType 0x7ed704e010 disconnect failed
[   +1 ms] D/ViewRootImpl[MainActivity](21175): surface should not be released
[   +2 ms] V/LifecycleChannel(21175): Sending AppLifecycleState.paused message.
[        ] V/DartMessenger(21175): Sending message with callback over channel 'flutter/lifecycle'
[ +274 ms] W/libEGL  (21175): EGLNativeWindowType 0x7ed704d010 disconnect failed
[  +35 ms] V/ActivityThread(21175): Handle window ActivityRecord{e0ef005 token=android.os.BinderProxy@650a038 {app.miiii.mibarrioapp/app.miiii.mibarrioapp.MainActivity}} visibility: false
[ +358 ms] D/ZrHung.AppEyeUiProbe(21175): Current Activity:false
[        ] D/ZrHung.AppEyeUiProbe(21175): not watching, wait.
[+4226 ms] E/        (21175): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]

**Flutter doctor**

[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F132, locale es-AR)
    • Flutter version 1.7.8+hotfix.2 at /Users/jrepetto/Desktop/flutter
    • Framework revision 2e540931f7 (2 weeks ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrepetto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • SNE LX3 • XXXXXXXXXXX • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by charafau** [comment]
Have you asked for camera permissions?

**Comment by kevinbayes** [comment]
I had the same issue, I just forked the repository and added: 
```
            public void onPermissionRequest(PermissionRequest request) {

                if(requestedPermissions.size() == 1 && requestedPermissions.get(0).equals("*")) {
                    request.grant(request.getResources());
                    return;
                }

                for(String resource : request.getResources()) {
                    if(!requestedPermissions.contains(resource)) {
                        request.deny();
                        return;
                    }
                }
                request.grant(request.getResources());
            }
```
To the webView.setWebChromeClient(new WebChromeClient() in WebviewManager. It was just a hack to try get it working, but if its helpful I can make it more formal and do a pull request. My usecase was WebRTC sessions.

**Comment by JeronimoRepetto** [comment]
@kevinbayes I did it but that didn't work
