### ISSUE TITLE
File Attachment Not working After embed in to native app

### ISSUE THREAD

**Issue by praveenb** [fluttercommunity/flutter_webview_plugin#495]
When i run in Flutter project code, i see i'm able to attach a file. But, Its not working, after embedding the Flutter code in to native app as a Fragment View. 

I see the reason is when run from Flutter project code, After attaching a file, It's calling Plugin's `onActivityResult `method. below is screenshot.

![image](https://user-images.githubusercontent.com/592596/62213603-e8a91a80-b3c0-11e9-89e4-b24f0cdddaa7.png)

But In embedded app, Its calling native app's  `onActivityResult ` result which doesn't have code for handling selected image.

Please help regarding this issue, how to make it work in embedded app.

Thanks for the wonderful webview plugin it helped a lot.
Thank you.

**Comment by RRRMannn** [comment]
hey bro how did you fix this problem ,i got the wrong  on my flutter project

**Comment by praveenb** [comment]
@RRRMannn, After waiting for long time on this fix. Instead using Flutter webview, I started Native App Screen with Webview. Solved the issue.
