### ISSUE TITLE
Not able to browse HTTP URL

### ISSUE THREAD

**Issue by JohnPang1204** [fluttercommunity/flutter_webview_plugin#545]
Hi everyone, that is worked fine for me if i run **https** type protocol like Google or Facebook but unfortunately it will shows error message when it change to **http** type of URL. Does anyone faced it before? Thank you.

Output:

**Https type of link(Google):**
![WhatsApp Image 2019-09-04 at 12 19 03 PM](https://user-images.githubusercontent.com/48014651/64225532-5986a980-cf0e-11e9-8c54-5669bb4739ac.jpeg)

**Http type of link(lujunhong2or.com):
![WhatsApp Image 2019-09-04 at 12 19 03 PM (1)](https://user-images.githubusercontent.com/48014651/64225545-699e8900-cf0e-11e9-958a-2265cb4e1523.jpeg)
**

**Comment by JohnPang1204** [comment]
` Widget build(BuildContext context) {
    return WebviewScaffold(
      url: "http://lujunhong2or.com/",
      appBar: AppBar(
        title: const Text('Widget WebView'),
      ),

      withZoom: true,
      withLocalStorage: true,
      initialChild: Container(
        color: Colors.redAccent,
        child: const Center(
          child: Text('Waiting.....'),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          children: <Widget>[
            IconButton(
              icon: const Icon(Icons.arrow_back_ios),
              onPressed: () {
                flutterWebViewPlugin.goBack();
              },
            ),
            IconButton(
              icon: const Icon(Icons.arrow_forward_ios),
              onPressed: () {
                flutterWebViewPlugin.goForward();
              },
            ),
            IconButton(
              icon: const Icon(Icons.autorenew),
              onPressed: () {
                flutterWebViewPlugin.reload();
              },
            ),
          ],
        ),
      ),
    );
  }`

**Comment by JohnPang1204** [comment]
Finally i have solved it. 
Here is the solution for those who facing the same issues:
https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https

**Comment by charafau** [comment]
@JohnPang1204  sorry I missed your issue. You probably want to disable clear text for release build and only use https. I will add note to documentation. Closing
