### ISSUE TITLE
minSdk version error

### ISSUE THREAD

**Issue by moyaying** [fluttercommunity/flutter_webview_plugin#548]
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Remove minSdkVersion and sync project
Affected Modules: flutter_webview_plugin-0.3.7-android-flutter_webview_plugin

**Comment by charafau** [comment]
Thanks for noticing this, I merged that PR but didn't think about gradle file. Will change, thanks

**Comment by charafau** [comment]
Published as `0.3.8`
