### ISSUE TITLE
Auth problem on android 9 

### ISSUE THREAD

**Issue by dhanrajvermaRepo** [fluttercommunity/flutter_webview_plugin#557]
I am sharing post from my flutter app to Social media platforms like linkedIn, facebook, twitter etc. So I have used flutter web view plugin 0.3.8(tried older versions also) to authenticate to social accounts. This plugin is working fine below android 9. In android 9 it is working on local (which uses http) but on production(which uses https) it is not working (authentication not working). I want to make it clear that it is working on android 5.1 in all aspects.

> Flutter doctor output

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at /Users/root-flutter/Documents/development/flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/root-flutter/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode10.3.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[!] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • RMX1805 • 269e796b • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by charafau** [comment]
is your certificate valid ?

**Comment by dhanrajvermaRepo** [comment]
> is your certificate valid ?

yes i have released my app with same certificate.

**Comment by charafau** [comment]
I was asking on you ssl certificate on server, not your app signing certificate
