### ISSUE TITLE
flutter_webview_plugin-0.3.8 build release apk has error

### ISSUE THREAD

**Issue by zhanghaigang666** [fluttercommunity/flutter_webview_plugin#568]
C:\Users\zhanghg\Desktop\flutter-book-master\robot_master_project>flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.9s
Resolving dependencies...                                           4.9s
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\zhanghg\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_webview_plugin-0.3.8\android\src\main\java\com\flutter_webview_plugin\WebviewManager.javaʹ����δ�����򲻰�ȫ�Ĳ��
���
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
Running Gradle task 'assembleRelease'...                                                                                                      C:\Users\zhanghg\Desktop\flutter-book-master\robot_master_projec
t\android\app\src\main\AndroidManifest.xml:22:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.1.0-alpha01] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-33:19 to override.
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     133.0s (!)
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by zhanghaigang666** [comment]
The above problem, I changed the gradle to 3.2.1, you can compile the release apk package, but the compiler will still report an error, but does not affect the compilation results.

Running Gradle task 'assembleDebug'...
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\zhanghg\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_webview_plugin-0.3.8\android\src\main\java\com\flutter_webview_plugin\WebviewManager.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Application finished.

**Comment by jnaval04** [comment]
I am actually getting the same error. I am using Flutter 1.9.1+hotfix.4.

**Comment by zhanghaigang666** [comment]
This error should be that the plugin uses an outdated api, and currently has no effect on the use of the plugin.

**Comment by charafau** [comment]
I see that you're also using appcompat not from androidX, migrate your project to it.
