### ISSUE TITLE
Permissions Location android

### ISSUE THREAD

**Issue by mgdecondux** [fluttercommunity/flutter_webview_plugin#570]
Hello, im need the location permission on my web view, i have a button to request this permission, in the browser  work fine but in the webview no work, the  pop-up with permission not shows, i added location permission in AndroidManifest.xml but nothing happened, can help me with this?

**Comment by charafau** [comment]
Previously I thought that this needs to be just set but it seems like this needs to be implemented:

https://stackoverflow.com/questions/5329662/android-webview-geolocation

Note that ios probably also needs that code, does it work on iOS ?

**Comment by mgdecondux** [comment]
Hello @charafau, 

I read previously your link, but i don´t know where add this lines, i search in the folder android, but only find the MainActivity.java and don´t see nothing about flutter_webview_plugin.

![image](https://user-images.githubusercontent.com/48256995/66003875-e587e480-e46c-11e9-918b-704cad51f44c.png)

**Comment by charafau** [comment]
@mgdecondux  that would have to be implemented into plugin

**Comment by mgdecondux** [comment]
Hey @joeyczz 

You have example about this?

**Comment by 919955081** [comment]
I also encountered this question,it not work when i set geolocationEnabled is ture，somebody help me

**Comment by Kay-coding** [comment]
I just solved this problem and added permissions internally.
![image](https://user-images.githubusercontent.com/22172803/67364967-3a69d700-f5a3-11e9-896b-1bf11fe6bbc5.png)

**Comment by mgdecondux** [comment]
Thanks @Kay-coding, i request the permission directly flutter, with the package https://pub.dev/packages/permission_handler.

**Comment by krongnang** [comment]
> I just solved this problem and added permissions internally.
> ![image](https://user-images.githubusercontent.com/22172803/67364967-3a69d700-f5a3-11e9-896b-1bf11fe6bbc5.png)

Hi @Kay-coding , could you please show me more explain or fully source code to allow browser get location by our app.
Thanks you
