### ISSUE TITLE
javascriptChannels not present in pub.dev release

### ISSUE THREAD

**Issue by ilangleben19** [fluttercommunity/flutter_webview_plugin#571]
The version of this plugin available as a Flutter package on pub.dev does not have any references to javascriptChannels. This is true both of the package installed by adding to pubspec.yaml and the archive downloadable from pub.dev. However, in the code in this repository, there are many references to javascriptChannels. For example, FlutterWebviewPlugin.launch accepts a javascriptChannels parameter in the git repo but not on pub.dev.

**Comment by alereisan** [comment]
@ilangleben19 I think it is not in the flutter package

anyhow I just got it to work by using:

```
  flutter_webview_plugin:
    git:
      url: git://github.com/fluttercommunity/flutter_webview_plugin.git
```

in pubspec.yaml

**Comment by ilangleben19** [comment]
That makes a lot of sense haha
I also fixed it (sketch) by opening the packages file and unzipping the git
repo into where pub was caching it. I also specified a specific version
number in pubspec.yaml to avoid the good version from being overwritten by
an update.

Thanks for the help!

**Comment by rano1996** [comment]
thank you 
it worked for me
