### ISSUE TITLE
No way to distinguish the URL of the main page from that of an iFrame

### ISSUE THREAD

**Issue by mav2287** [fluttercommunity/flutter_webview_plugin#589]
There doesn't seem to be any way to distinguish the URL of the main page from an iFrame. With the native iOS webview you could use something like:

`if request.url?.absoluteString == request.mainDocumentURL?.absoluteString`

However, with this when watching onUrlChanged and onStateChanged I can't seem to see anything that would allow you to distinguish between an iframe and the main page the iframe is embedded in. How do you tell the two apart?

## System info

Issue occurs on: / both
Plugin version: 0.3.8
Flutter doctor output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] Connected device (1 available)
• No issues found!

**Comment by charafau** [comment]
I guess you could use some javascript and `eval` function to do that
