### ISSUE TITLE
There was a problem exporting the apk, andriod X is not supported

### ISSUE THREAD

**Issue by Frank0945** [fluttercommunity/flutter_webview_plugin#618]
Just run "flutter build apk"
---

Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      55.1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_webview_plugin...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    1.0s
         *********************************************************
WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_webview_plugin'.
> The SDK directory 'C:\Users\Gloria\AppData\Local\Android\Sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

The plugin flutter_webview_plugin could not be built due to the issue above.

**Comment by jans-y** [comment]
I have fixed it locally by removing this file:

```/android/local.properties```

**Comment by ltoenjes** [comment]
As the comments in that file suggests, it should not have been checked out into version control in the first place..

**Comment by joelcho** [comment]
@jans-y 
Thanks, it works for me.
By removing local.properties and add ANDROID_HOME environment variable

**Comment by xuexiangjys** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by xuexiangjys** [comment]
I solved it.

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Comment by charafau** [comment]
my bad. lessons learned, not use other pcs when fixing bugs. thanks! should be fixed in 0.3.10+1

**Comment by Chethansmash7** [comment]
> As the comments in that file suggests, it should not have been checked out into version control in the first place..

Even I have the same problem.Which file are you talking about?

**Comment by Chethansmash7** [comment]
> I have fixed it locally by removing this file:
> 
> `/android/local.properties`
> 
> not in your project but in the folder where this plugin is situated:
> 
> In my case:
> `/Users/....../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.9+1/android/`

I tried.,but still doesnt work out
