### ISSUE TITLE
Haven't adapted androidx yet, I can't use it in my project

### ISSUE THREAD

**Issue by leafmi** [fluttercommunity/flutter_webview_plugin#646]
AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0-rc01' is set to compileOnly/provided which is not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_webview_plugin...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin flutter_webview_plugin could not be built due to the issue above.

**Comment by ZeroMoment** [comment]
hello, this error, how to solve

**Comment by leafmi** [comment]
I ended up using the source code directly, rebuilt

**Comment by leafmi** [comment]
> hello, this error, how to solve

I ended up using the source code directly, rebuilt

**Comment by OzzyOzmen** [comment]
it works for me because I did some changes and also i don't need to buttons for navigate to vewview full screen. And added app bar in sec screen.

it was hard to manage it because this is a complicated codes and set with no plan I guess :) btw thanks for share us. 

I can send with success version if anyone need.
