### ISSUE TITLE
Can't open a PDF file inside a Webview 

### ISSUE THREAD

**Issue by BIhab** [fluttercommunity/flutter_webview_plugin#733]
Hi, 
As mentioned in the title, my issue is quite simple: I have a Website we're I generate contract - a pdf file - and I can't open this contact on a Webview on flutter, when I click nothing happen, The PDF file is create with dompdf.

**Comment by narimetisaigopi** [comment]
did you get solution bro?

**Comment by BIhab** [comment]
> did you get solution bro?

Not yet ... :/

**Comment by deepakrana0011** [comment]
i am getting the same problem .. @BIhab get any solution for this

**Comment by BIhab** [comment]
> i am getting the same problem .. @BIhab get any solution for this

Not yet, I'm waiting for the help too, still no response.
