### ISSUE TITLE
Is there any feature like navigationDelegate of webview_flutter?

### ISSUE THREAD

**Issue by DesmondX** [fluttercommunity/flutter_webview_plugin#754]
As I said in the title,  I would be much appreciated if there would be something like navigationDelegate to help me to decide whether should launch some url or not.

**Comment by RaashVision** [comment]
No one responding to this feature request :(

**Comment by krongnang** [comment]
@charafau any update?

**Comment by krongnang** [comment]
@DesmondX  Did you resolve this problem?

**Comment by charafau** [comment]
Please check readme file - we try not to add new features and focus on official web view plugin
