### ISSUE TITLE
Crash ios release

### ISSUE THREAD

**Issue by fly512** [fluttercommunity/flutter_webview_plugin#77]
```

0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | +[NSException raise:format:]
3 Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
4 Flutter | -[FlutterStandardWriter writeValue:] + 1900
5 Flutter | -[FlutterStandardMethodCodec encodeMethodCall:] + 156
6 Flutter | -[FlutterMethodChannel invokeMethod:arguments:] + 64
7 Runner | -[FlutterWebviewPlugin webView:didFailNavigation:withError:] (FlutterWebviewPlugin.m:182)
8 WebKit | 0x00000001929f2000 + 590840
9 WebKit | 0x00000001929f2000 + 2409200
10 WebKit | 0x00000001929f2000 + 2543708
11 WebKit | 0x00000001929f2000 + 574908
12 WebKit | 0x00000001929f2000 + 2927188
13 WebKit | 0x00000001929f2000 + 325868
14 WebKit | 0x00000001929f2000 + 336628
15 JavaScriptCore | WTF::RunLoop::performWork() + 268
16 JavaScriptCore | WTF::RunLoop::performWork(void*) + 36
17 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
18 CoreFoundation | ___CFRunLoopDoSources0 + 276
19 CoreFoundation | ___CFRunLoopRun + 1204
20 CoreFoundation | CFRunLoopRunSpecific + 552
21 GraphicsServices | GSEventRunModal + 100
22 UIKit | UIApplicationMain + 236


```

**Comment by zoechi** [comment]
How to reproduce?
Please post the output of `flutter doctor`.
What webview-plugin version are you using (from `pubspec.lock`)

**Comment by fly512** [comment]
flutter_webview_plugin: "^0.1.5"

iPhone 6 Plus
11.3.1 (15E302)


```
[✓] Flutter (Channel unknown, v0.4.4, on Mac OS X 10.12.6 16G1314, locale zh-Hans-CN)
    • Flutter version 0.4.4 at /Users/mayonghui/Desktop/workspace/flutter
    • Framework revision f9bb4289e9 (2 days ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1
```

**Comment by deligence** [comment]
I'm also getting the similar fatal exception. 

`Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x184cfad8c __exceptionPreprocess
1  libobjc.A.dylib                0x183eb45ec objc_exception_throw
2  CoreFoundation                 0x184cfabf8 +[NSException raise:format:]
3  Foundation                     0x1856eafa0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  Flutter                        0x1052f8654 (Missing)
5  Flutter                        0x1052f8ca8 (Missing)
6  Flutter                        0x1052edb98 (Missing)
7  Runner                         0x1043259a4 -[FlutterWebviewPlugin webView:didFailNavigation:withError:] (FlutterWebviewPlugin.m:248)
8  WebKit                         0x1946aa3f8 WebKit::NavigationState::NavigationClient::didFailNavigationWithError(WebKit::WebPageProxy&, WebKit::WebFrameProxy&, API::Navigation*, WebCore::ResourceError const&, API::Object*)
9  WebKit                         0x1948662f0 WebKit::WebPageProxy::didFailLoadForFrame(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&)
10 WebKit                         0x19488705c void IPC::handleMessage<Messages::WebPageProxy::DidFailLoadForFrame, WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&)>(IPC::Decoder&, WebKit::WebPageProxy*, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WebCore::ResourceError const&, WebKit::UserData const&))
11 WebKit                         0x1946a65bc IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
12 WebKit                         0x1948e4a54 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
13 WebKit                         0x1946698ec IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
14 WebKit                         0x19466c2f4 IPC::Connection::dispatchOneMessage()
15 JavaScriptCore                 0x18c2ffe98 WTF::RunLoop::performWork()
16 JavaScriptCore                 0x18c300158 WTF::RunLoop::performWork(void*)
17 CoreFoundation                 0x184ca3404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
18 CoreFoundation                 0x184ca2c2c __CFRunLoopDoSources0
19 CoreFoundation                 0x184ca079c __CFRunLoopRun
20 CoreFoundation                 0x184bc0da8 CFRunLoopRunSpecific
21 GraphicsServices               0x186ba3020 GSEventRunModal
22 UIKit                          0x18eba178c UIApplicationMain
23 Runner                         0x1041e4974 main (main.m:7)
24 libdyld.dylib                  0x184651fc0 start`

flutter_webview_plugin: ^0.2.1+2
 iPhone 7 [iOS 11.3.0 (15E216)]
