### ISSUE TITLE
Opening a local url for development purposes

### ISSUE THREAD

**Issue by NickBrooks** [fluttercommunity/flutter_webview_plugin#92]
Normal websites are fine but opening a page on localhost isn't working. How do I get this working, does it require extra permissions?

![localhost](https://user-images.githubusercontent.com/4286755/40882803-c2278960-6730-11e8-8f8e-14609481f2c5.JPG)

**Comment by Kleak** [comment]
Duplicate #23

**Comment by zoechi** [comment]
Are you aware that `localhost` is the phone, not your development PC?
https://stackoverflow.com/questions/49855754/unable-to-make-calls-to-localhost-using-flutter-random-port-being-assigned-to-h/49855877#49855877 might provide some ideas.

**Comment by marcosgallardo** [comment]
I'm using `http://10.0.2.2/` for `localhost` server.
Everything else works but not this.

![Screenshot_1558718308](https://user-images.githubusercontent.com/4549886/58345506-e8bff380-7e2e-11e9-97f5-9d66a3c31f9c.png)

I tried [`android:usesCleartextTraffic="true"`](https://stackoverflow.com/a/52708032/3791844) and did not work.

Does anyone know what should I do?

**Comment by marcosgallardo** [comment]
@NickBrooks did you tried using [10.0.2.2](https://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator) instead of `localhost`

**Comment by muffinjello** [comment]
If it's just a static local file, see #349

**Comment by charafau** [comment]
`localhost` doesn't work because server is not running on your phone, but on your computer, use your computer ip, instead of `localhost`. closing.

**Comment by zoha-shobbar** [comment]
i have same issu,
> @NickBrooks did you tried using [10.0.2.2](https://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator) instead of `localhost`?

i did it but it not work
