### ISSUE TITLE
How to load a new url in WebviewScaffold?

### ISSUE THREAD

**Issue by jow-ct** [fluttercommunity/flutter_webview_plugin#98]
Hi,

I don't get it how to load a new url when using `WebviewScaffold`. I put some IconButton in the appBar.actions, but what to do there?

I tried 
```
  String url = "http:...";
  final webView = FlutterWebviewPlugin();

  ...new WebviewScaffold(
    url: url,
  ...
    onPressed: () => setState(() => url = "http:newone...")
  ...
    onPressed: () {webView.launch(newurl);}
  ...
    onPressed: () {webView.close(); webview.launch(newurl);}
    }
```

But all three ways did not work.

setState did not reload a new URL. Only launch throws an error ` java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.` And the close/launch idea made the webview fullscreen over the appBar.

Is there a solution?

**Comment by splitbrain** [comment]
I'm facing the same problem. I have buttons in the bottomNavigationBar that open a new activity. To make that activity visible I had to call webView.close(), but I don't see how I can reopen the webView() when I return to the WebviewScaffold activity.

**Comment by zoechi** [comment]
Looks like `setState()` is called on a different component. If you use `bottomNavigationBar` it's probably not a parent of the widget that contains `new WebviewScaffold()` and therefore won't be rebuilt. You might need to use a Stream and a StreamBuilder around `new FlutterWebviewPlugin()` and to notifiy the right widget to rebuild.

**Comment by jordansilva** [comment]
I don't know if it's correct, but I'm doing this way (I know this is by far not the best way to make this work properly, but it's working now):
```flutter
Future openNewActivity(BuildContext context) async {
    _flutterWebView.hide();

    await Navigator.push(context, new NavigationRoute(builder: (context) => new ListScreen()));

    Future.delayed(Duration(milliseconds: 350), () => _flutterWebView.show());
  }
````
_flutterWebView is FlutterWebviewPlugin.

**Comment by dao-wkm** [comment]
Its work for me
`Future _launcNewUrl(url) async {
      await _flutterWebViewPlugin.reloadUrl(url);
  }`

**Comment by dao-wkm** [comment]
Try to use `_flutterWebViewPlugin.reloadUrl(newUrl);`
